# Generated by Django 5.2.8 on 2026-01-13 02:27

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import saleor.core.utils.json_serializer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0096_newslettersubscription'),
        ('product', '0202_category_product_category_tree_id_lf1e1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('images', models.JSONField(blank=True, default=list, help_text='List of image URLs for the review')),
                ('helpful_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='Whether the reviewer has purchased this product')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to='account.user')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='productreview_p_meta_idx'), django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='productreview_meta_idx'), models.Index(fields=['product', 'status', '-created_at'], name='product_pro_product_fe5cf8_idx'), models.Index(fields=['user', '-created_at'], name='product_pro_user_id_99414b_idx'), models.Index(fields=['product', 'rating'], name='product_pro_product_8dd964_idx'), django.contrib.postgres.indexes.BTreeIndex(fields=['helpful_count'], name='product_pro_helpful_ae49e4_btree')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='product_review_rating_range')],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Email address to notify (required for guest users)', max_length=254)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the alert is active')),
                ('notified_at', models.DateTimeField(blank=True, help_text='When the user was last notified', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='product.productvariant')),
                ('user', models.ForeignKey(blank=True, help_text='User account if subscribed while logged in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_alerts', to='account.user')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['product_variant', 'is_active'], name='product_sto_product_da2247_idx'), models.Index(fields=['email', 'is_active'], name='product_sto_email_598d1c_idx'), models.Index(fields=['user', 'is_active'], name='product_sto_user_id_face35_idx'), models.Index(fields=['is_active', '-created_at'], name='product_sto_is_acti_9b5fe1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('product_variant', 'email'), name='unique_active_stock_alert')],
            },
        ),
    ]
