# Generated by Django 5.2.8 on 2026-01-13 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0096_newslettersubscription'),
        ('product', '0203_productreview_stockalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReviewHelpfulVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_identifier', models.CharField(blank=True, help_text='IP address or session ID for guest users', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='product.productreview')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='account.user')),
            ],
            options={
                'indexes': [models.Index(fields=['review', 'user'], name='product_pro_review__9a247f_idx'), models.Index(fields=['review', 'guest_identifier'], name='product_pro_review__6a6222_idx')],
                'unique_together': {('review', 'guest_identifier'), ('review', 'user')},
            },
        ),
    ]
