/**
 * Protein House - Store Configuration
 * ================================
 * Generated by init-new-store.ps1
 * Date: 2026-04-02 11:59:43
 * Store Type: physical
 */

import { createStoreConfig, StoreConfig } from '../store.config';

export const protein-houseConfig: StoreConfig = createStoreConfig('physical', {
  store: {
    name: "Protein House",
    tagline: "Premium Sports Nutrition",
    type: "physical",
    description: "Welcome to Protein House - Premium Sports Nutrition",
    email: "support@proteinhouse.com",
    phone: "+1 (555) 123-4567",
    address: {
      street: "",
      city: "",
      state: "",
      zip: "",
      country: "",
    },
  },

  branding: {
    logo: "/logo.svg",
    logoAlt: "Protein House Logo",
    favicon: "/favicon.ico",

    colors: {
      primary: "#E11D48",
      secondary: "#1F2937",
      accent: "#F59E0B",
      background: "#FFFFFF",
      surface: "#F9FAFB",
      text: "#111827",
      textMuted: "#6B7280",
      success: "#059669",
      warning: "#D97706",
      error: "#DC2626",
    },

    typography: {
      fontHeading: "Inter",
      fontBody: "Inter",
      fontMono: "JetBrains Mono",
    },

    style: {
      borderRadius: "md",
      buttonStyle: "solid",
      cardShadow: "sm",
    },
  },

  seo: {
    titleTemplate: "%s | Protein House",
    defaultTitle: "Protein House - Premium Sports Nutrition",
    defaultDescription: "Shop at Protein House. Premium Sports Nutrition",
    defaultImage: "/og-image.jpg",
    twitterHandle: null,
  },

  integrations: {
    analytics: {
      googleAnalyticsId: null,
      googleTagManagerId: null,
      facebookPixelId: null,
      hotjarId: null,
    },
    marketing: {
      mailchimpListId: null,
      klaviyoApiKey: null,
    },
    support: {
      intercomAppId: null,
      zendeskKey: null,
      crispWebsiteId: null,
    },
    social: {
      facebook: null,
      instagram: null,
      twitter: null,
      youtube: null,
      tiktok: null,
      pinterest: null,
    },
  },

  localization: {
    defaultLocale: "en-US",
    supportedLocales: ["en-US"],
    dateFormat: "MM/DD/YYYY",
    timeFormat: "12h",
  },
});

export default protein-houseConfig;