export type ProductType = "shoes" | "tops" | "bottoms" | "accessories";
export type Gender = "Men" | "Women" | "Kids" | "Unisex";
export type Brand = "Nike" | "Adidas" | "Under Armour" | "Skechers" | "ASICS" | "Reebok" | "Puma";

export interface ProductDefinition {
  type: ProductType;
  brand: Brand;
  model: string;
  model_he: string;
  gender: Gender;
  category: string;
  material: string;
  style?: string; // For shoes
  productType?: string; // For tops/bottoms/accessories
  basePrice_ILS: number;
  basePrice_USD: number;
  discount?: number; // 0-0.5 (0% to 50%)
  collections: string[];
}

// Shoes (40 products)
export const SHOES_PRODUCTS: ProductDefinition[] = [
  // Nike Running (6)
  {
    type: "shoes",
    brand: "Nike",
    model: "Air Max 90",
    model_he: "אייר מקס 90",
    gender: "Men",
    category: "men-running-shoes",
    material: "Synthetic",
    style: "Running",
    basePrice_ILS: 549,
    basePrice_USD: 148,
    collections: ["nike", "mens-collection", "best-sellers"],
  },
  {
    type: "shoes",
    brand: "Nike",
    model: "Revolution 6",
    model_he: "רבולושן 6",
    gender: "Men",
    category: "men-running-shoes",
    material: "Mesh",
    style: "Running",
    basePrice_ILS: 399,
    basePrice_USD: 108,
    discount: 0.15,
    collections: ["nike", "mens-collection", "sale"],
  },
  {
    type: "shoes",
    brand: "Nike",
    model: "Pegasus 40",
    model_he: "פגסוס 40",
    gender: "Women",
    category: "women-running-shoes",
    material: "Mesh",
    style: "Running",
    basePrice_ILS: 599,
    basePrice_USD: 162,
    collections: ["nike", "womens-collection", "new-arrivals"],
  },
  {
    type: "shoes",
    brand: "Nike",
    model: "Zoom Fly 5",
    model_he: "זום פליי 5",
    gender: "Men",
    category: "men-running-shoes",
    material: "Mesh",
    style: "Running",
    basePrice_ILS: 749,
    basePrice_USD: 202,
    collections: ["nike", "mens-collection", "featured-products"],
  },
  {
    type: "shoes",
    brand: "Nike",
    model: "Downshifter 12",
    model_he: "דאונשיפטר 12",
    gender: "Women",
    category: "women-running-shoes",
    material: "Synthetic",
    style: "Running",
    basePrice_ILS: 349,
    basePrice_USD: 94,
    discount: 0.20,
    collections: ["nike", "womens-collection", "sale"],
  },
  {
    type: "shoes",
    brand: "Nike",
    model: "Star Runner 3",
    model_he: "סטאר ראנר 3",
    gender: "Kids",
    category: "kids-sport-shoes",
    material: "Synthetic",
    style: "Running",
    basePrice_ILS: 249,
    basePrice_USD: 67,
    collections: ["nike", "kids-collection"],
  },

  // Adidas Running (5)
  {
    type: "shoes",
    brand: "Adidas",
    model: "Ultraboost 22",
    model_he: "אולטרהבוסט 22",
    gender: "Men",
    category: "men-running-shoes",
    material: "Mesh",
    style: "Running",
    basePrice_ILS: 799,
    basePrice_USD: 216,
    collections: ["adidas", "mens-collection", "best-sellers"],
  },
  {
    type: "shoes",
    brand: "Adidas",
    model: "Supernova 2",
    model_he: "סופרנובה 2",
    gender: "Women",
    category: "women-running-shoes",
    material: "Mesh",
    style: "Running",
    basePrice_ILS: 499,
    basePrice_USD: 135,
    discount: 0.25,
    collections: ["adidas", "womens-collection", "sale"],
  },
  {
    type: "shoes",
    brand: "Adidas",
    model: "Duramo SL",
    model_he: "דוראמו SL",
    gender: "Men",
    category: "men-running-shoes",
    material: "Synthetic",
    style: "Running",
    basePrice_ILS: 349,
    basePrice_USD: 94,
    collections: ["adidas", "mens-collection"],
  },
  {
    type: "shoes",
    brand: "Adidas",
    model: "Solar Glide 5",
    model_he: "סולאר גליד 5",
    gender: "Women",
    category: "women-running-shoes",
    material: "Mesh",
    style: "Running",
    basePrice_ILS: 649,
    basePrice_USD: 175,
    collections: ["adidas", "womens-collection", "new-arrivals"],
  },
  {
    type: "shoes",
    brand: "Adidas",
    model: "RapidaRun",
    model_he: "רפידה ראן",
    gender: "Kids",
    category: "kids-casual-shoes",
    material: "Synthetic",
    style: "Running",
    basePrice_ILS: 229,
    basePrice_USD: 62,
    collections: ["adidas", "kids-collection"],
  },

  // Nike Training (4)
  {
    type: "shoes",
    brand: "Nike",
    model: "Metcon 8",
    model_he: "מטקון 8",
    gender: "Men",
    category: "men-training-shoes",
    material: "Synthetic",
    style: "Training",
    basePrice_ILS: 649,
    basePrice_USD: 175,
    collections: ["nike", "mens-collection", "featured-products"],
  },
  {
    type: "shoes",
    brand: "Nike",
    model: "Free X Metcon 3",
    model_he: "פרי X מטקון 3",
    gender: "Women",
    category: "women-training-shoes",
    material: "Mesh",
    style: "Training",
    basePrice_ILS: 549,
    basePrice_USD: 148,
    discount: 0.15,
    collections: ["nike", "womens-collection", "sale"],
  },
  {
    type: "shoes",
    brand: "Nike",
    model: "SuperRep Go 3",
    model_he: "סופר רפ גו 3",
    gender: "Men",
    category: "men-training-shoes",
    material: "Mesh",
    style: "Training",
    basePrice_ILS: 499,
    basePrice_USD: 135,
    collections: ["nike", "mens-collection"],
  },
  {
    type: "shoes",
    brand: "Nike",
    model: "Renew In-Season TR 12",
    model_he: "רניו אין סיזן TR 12",
    gender: "Women",
    category: "women-training-shoes",
    material: "Synthetic",
    style: "Training",
    basePrice_ILS: 399,
    basePrice_USD: 108,
    collections: ["nike", "womens-collection"],
  },

  // Adidas Training (4)
  {
    type: "shoes",
    brand: "Adidas",
    model: "Dropset Trainer",
    model_he: "דרופסט טריינר",
    gender: "Men",
    category: "men-training-shoes",
    material: "Synthetic",
    style: "Training",
    basePrice_ILS: 599,
    basePrice_USD: 162,
    collections: ["adidas", "mens-collection", "new-arrivals"],
  },
  {
    type: "shoes",
    brand: "Adidas",
    model: "Alphaboost V1",
    model_he: "אלפהבוסט V1",
    gender: "Women",
    category: "women-training-shoes",
    material: "Mesh",
    style: "Training",
    basePrice_ILS: 529,
    basePrice_USD: 143,
    discount: 0.20,
    collections: ["adidas", "womens-collection", "sale"],
  },
  {
    type: "shoes",
    brand: "Adidas",
    model: "GameCourt 2",
    model_he: "גיימקורט 2",
    gender: "Men",
    category: "men-training-shoes",
    material: "Synthetic",
    style: "Training",
    basePrice_ILS: 449,
    basePrice_USD: 121,
    collections: ["adidas", "mens-collection"],
  },
  {
    type: "shoes",
    brand: "Adidas",
    model: "CrazyFlight",
    model_he: "קרייזי פלייט",
    gender: "Women",
    category: "women-training-shoes",
    material: "Mesh",
    style: "Training",
    basePrice_ILS: 479,
    basePrice_USD: 129,
    collections: ["adidas", "womens-collection"],
  },

  // Soccer Shoes (6)
  {
    type: "shoes",
    brand: "Nike",
    model: "Mercurial Vapor 15",
    model_he: "מרקוריאל ויפור 15",
    gender: "Men",
    category: "men-soccer-shoes",
    material: "Synthetic",
    style: "Soccer",
    basePrice_ILS: 749,
    basePrice_USD: 202,
    collections: ["nike", "mens-collection", "best-sellers"],
  },
  {
    type: "shoes",
    brand: "Nike",
    model: "Phantom GX Elite",
    model_he: "פנטום GX אליט",
    gender: "Men",
    category: "men-soccer-shoes",
    material: "Synthetic",
    style: "Soccer",
    basePrice_ILS: 899,
    basePrice_USD: 243,
    collections: ["nike", "mens-collection", "featured-products"],
  },
  {
    type: "shoes",
    brand: "Adidas",
    model: "Predator Edge.1",
    model_he: "פרדטור אדג'.1",
    gender: "Men",
    category: "men-soccer-shoes",
    material: "Synthetic",
    style: "Soccer",
    basePrice_ILS: 849,
    basePrice_USD: 229,
    collections: ["adidas", "mens-collection", "best-sellers"],
  },
  {
    type: "shoes",
    brand: "Adidas",
    model: "Copa Pure 2",
    model_he: "קופה פיור 2",
    gender: "Men",
    category: "men-soccer-shoes",
    material: "Leather",
    style: "Soccer",
    basePrice_ILS: 699,
    basePrice_USD: 189,
    discount: 0.15,
    collections: ["adidas", "mens-collection", "sale"],
  },
  {
    type: "shoes",
    brand: "Adidas",
    model: "X Speedportal.3",
    model_he: "X ספידפורטל.3",
    gender: "Men",
    category: "men-soccer-shoes",
    material: "Synthetic",
    style: "Soccer",
    basePrice_ILS: 549,
    basePrice_USD: 148,
    collections: ["adidas", "mens-collection"],
  },
  {
    type: "shoes",
    brand: "Nike",
    model: "Tiempo Legend 9",
    model_he: "טיאמפו לג'נד 9",
    gender: "Men",
    category: "men-soccer-shoes",
    material: "Leather",
    style: "Soccer",
    basePrice_ILS: 799,
    basePrice_USD: 216,
    collections: ["nike", "mens-collection"],
  },

  // Casual Shoes (8)
  {
    type: "shoes",
    brand: "Nike",
    model: "Air Force 1",
    model_he: "אייר פורס 1",
    gender: "Men",
    category: "men-casual-shoes",
    material: "Leather",
    style: "Casual",
    basePrice_ILS: 499,
    basePrice_USD: 135,
    collections: ["nike", "mens-collection", "best-sellers"],
  },
  {
    type: "shoes",
    brand: "Nike",
    model: "Court Vision Low",
    model_he: "קורט ויז'ן לואו",
    gender: "Women",
    category: "women-casual-shoes",
    material: "Synthetic",
    style: "Casual",
    basePrice_ILS: 399,
    basePrice_USD: 108,
    discount: 0.20,
    collections: ["nike", "womens-collection", "sale"],
  },
  {
    type: "shoes",
    brand: "Adidas",
    model: "Stan Smith",
    model_he: "סטן סמית",
    gender: "Men",
    category: "men-casual-shoes",
    material: "Leather",
    style: "Casual",
    basePrice_ILS: 449,
    basePrice_USD: 121,
    collections: ["adidas", "mens-collection", "best-sellers"],
  },
  {
    type: "shoes",
    brand: "Adidas",
    model: "Superstar",
    model_he: "סופרסטאר",
    gender: "Women",
    category: "women-casual-shoes",
    material: "Leather",
    style: "Casual",
    basePrice_ILS: 479,
    basePrice_USD: 129,
    collections: ["adidas", "womens-collection", "featured-products"],
  },
  {
    type: "shoes",
    brand: "Skechers",
    model: "D'Lites",
    model_he: "די'לייטס",
    gender: "Women",
    category: "women-casual-shoes",
    material: "Synthetic",
    style: "Casual",
    basePrice_ILS: 349,
    basePrice_USD: 94,
    collections: ["skechers", "womens-collection"],
  },
  {
    type: "shoes",
    brand: "Skechers",
    model: "Go Walk 6",
    model_he: "גו ווק 6",
    gender: "Men",
    category: "men-casual-shoes",
    material: "Mesh",
    style: "Casual",
    basePrice_ILS: 329,
    basePrice_USD: 89,
    discount: 0.25,
    collections: ["skechers", "mens-collection", "sale"],
  },
  {
    type: "shoes",
    brand: "ASICS",
    model: "Gel-Lyte III",
    model_he: "ג'ל-לייט III",
    gender: "Men",
    category: "men-casual-shoes",
    material: "Synthetic",
    style: "Casual",
    basePrice_ILS: 549,
    basePrice_USD: 148,
    collections: ["asics", "mens-collection", "new-arrivals"],
  },
  {
    type: "shoes",
    brand: "Puma",
    model: "Suede Classic",
    model_he: "זמש קלאסי",
    gender: "Women",
    category: "women-casual-shoes",
    material: "Leather",
    style: "Casual",
    basePrice_ILS: 399,
    basePrice_USD: 108,
    collections: ["puma", "womens-collection"],
  },

  // Additional products continue...
  // Skechers/ASICS/Reebok/Under Armour mix (7 more shoes to reach 40 total)
  {
    type: "shoes",
    brand: "Under Armour",
    model: "HOVR Phantom 3",
    model_he: "HOVR פנטום 3",
    gender: "Men",
    category: "men-running-shoes",
    material: "Mesh",
    style: "Running",
    basePrice_ILS: 649,
    basePrice_USD: 175,
    collections: ["under-armour", "mens-collection"],
  },
  {
    type: "shoes",
    brand: "Under Armour",
    model: "Charged Assert 10",
    model_he: "צ'רג'ד אסרט 10",
    gender: "Women",
    category: "women-running-shoes",
    material: "Mesh",
    style: "Running",
    basePrice_ILS: 429,
    basePrice_USD: 116,
    discount: 0.15,
    collections: ["under-armour", "womens-collection", "sale"],
  },
  {
    type: "shoes",
    brand: "Reebok",
    model: "Nano X3",
    model_he: "ננו X3",
    gender: "Men",
    category: "men-training-shoes",
    material: "Synthetic",
    style: "Training",
    basePrice_ILS: 599,
    basePrice_USD: 162,
    collections: ["reebok", "mens-collection"],
  },
  {
    type: "shoes",
    brand: "Reebok",
    model: "Club C 85",
    model_he: "קלאב C 85",
    gender: "Women",
    category: "women-casual-shoes",
    material: "Leather",
    style: "Casual",
    basePrice_ILS: 379,
    basePrice_USD: 102,
    collections: ["reebok", "womens-collection"],
  },
  {
    type: "shoes",
    brand: "ASICS",
    model: "GT-2000 11",
    model_he: "GT-2000 11",
    gender: "Men",
    category: "men-running-shoes",
    material: "Mesh",
    style: "Running",
    basePrice_ILS: 699,
    basePrice_USD: 189,
    collections: ["asics", "mens-collection", "best-sellers"],
  },
  {
    type: "shoes",
    brand: "ASICS",
    model: "Gel-Cumulus 25",
    model_he: "ג'ל-קומולוס 25",
    gender: "Women",
    category: "women-running-shoes",
    material: "Mesh",
    style: "Running",
    basePrice_ILS: 629,
    basePrice_USD: 170,
    collections: ["asics", "womens-collection"],
  },
  {
    type: "shoes",
    brand: "Skechers",
    model: "Max Cushioning Elite",
    model_he: "מקס קושינינג אליט",
    gender: "Men",
    category: "men-running-shoes",
    material: "Mesh",
    style: "Running",
    basePrice_ILS: 449,
    basePrice_USD: 121,
    discount: 0.30,
    collections: ["skechers", "mens-collection", "sale"],
  },
];

import { TOPS_PRODUCTS, BOTTOMS_PRODUCTS, ACCESSORIES_PRODUCTS } from "./additional-products";

export const ALL_PRODUCTS = [
  ...SHOES_PRODUCTS,
  ...TOPS_PRODUCTS,
  ...BOTTOMS_PRODUCTS,
  ...ACCESSORIES_PRODUCTS,
];
