# PowerShell script to configure tunnel URLs for all services
# This helps set the correct API URLs when using tunnels

param(
    [Parameter(Mandatory = $true)]
    [string]$ApiTunnelUrl,
    
    [Parameter(Mandatory = $false)]
    [string]$DashboardTunnelUrl = "",
    
    [Parameter(Mandatory = $false)]
    [string]$StripeTunnelUrl = "",
    
    [Parameter(Mandatory = $false)]
    [string]$StorefrontTunnelUrl = ""
)

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Configuring Tunnel URLs" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Validate API tunnel URL
if (-not $ApiTunnelUrl) {
    Write-Host "Error: API tunnel URL is required" -ForegroundColor Red
    Write-Host "Usage: .\configure-tunnel-urls.ps1 -ApiTunnelUrl 'https://your-api.trycloudflare.com'" -ForegroundColor Yellow
    exit 1
}

# Ensure API URL ends with /graphql/
if (-not $ApiTunnelUrl.EndsWith("/graphql/")) {
    if (-not $ApiTunnelUrl.EndsWith("/")) {
        $ApiTunnelUrl = "$ApiTunnelUrl/graphql/"
    }
    else {
        $ApiTunnelUrl = "$ApiTunnelUrlgraphql/"
    }
}

Write-Host "API Tunnel URL: $ApiTunnelUrl" -ForegroundColor Yellow
Write-Host ""

# Create or update .env file in infra directory
$envFile = Join-Path $PSScriptRoot "..\.env"
$envContent = @"

# Tunnel URLs Configuration
# Generated by configure-tunnel-urls.ps1
# These URLs are used when accessing services via tunnels

# Saleor API (GraphQL endpoint)
DASHBOARD_API_URL=$ApiTunnelUrl
"@

# Add Dashboard tunnel URL if provided
if ($DashboardTunnelUrl) {
    Write-Host "Dashboard Tunnel URL: $DashboardTunnelUrl" -ForegroundColor Yellow
}

# Add Stripe tunnel URL if provided
if ($StripeTunnelUrl) {
    Write-Host "Stripe Tunnel URL: $StripeTunnelUrl" -ForegroundColor Yellow
    $envContent += "`nSTRIPE_APP_URL=$StripeTunnelUrl"
}

# Add Storefront tunnel URL if provided
if ($StorefrontTunnelUrl) {
    Write-Host "Storefront Tunnel URL: $StorefrontTunnelUrl" -ForegroundColor Yellow
    $envContent += "`nNEXT_PUBLIC_STOREFRONT_URL=$StorefrontTunnelUrl"
}

Write-Host ""
Write-Host "Writing configuration to .env file..." -ForegroundColor Cyan

# Append to .env file (create if doesn't exist)
if (Test-Path $envFile) {
    # Remove old tunnel configuration if exists
    $existingContent = Get-Content $envFile -Raw
    $lines = $existingContent -split "`n"
    $filteredLines = $lines | Where-Object { 
        $_ -notmatch "^# Tunnel URLs Configuration" -and
        $_ -notmatch "^# Generated by configure-tunnel-urls" -and
        $_ -notmatch "^DASHBOARD_API_URL=" -and
        $_ -notmatch "^STRIPE_APP_URL=" -and
        $_ -notmatch "^NEXT_PUBLIC_STOREFRONT_URL=" -and
        $_ -notmatch "^$" -or ($_ -match "^$" -and $prevLine -notmatch "^# Tunnel")
    }
    $prevLine = ""
    $newContent = ($filteredLines | Where-Object { $_.Trim() -ne "" }) -join "`n"
    $newContent += "`n`n$envContent"
    Set-Content -Path $envFile -Value $newContent
}
else {
    Set-Content -Path $envFile -Value $envContent
}

Write-Host "Configuration saved to: $envFile" -ForegroundColor Green
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Next Steps:" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "1. Restart the services to apply changes:" -ForegroundColor Yellow
Write-Host "   docker compose -f infra/docker-compose.dev.yml restart saleor-dashboard saleor-storefront saleor-stripe-app" -ForegroundColor White
Write-Host ""
Write-Host "2. Verify CORS is configured (should allow all origins in dev):" -ForegroundColor Yellow
Write-Host "   Check that ALLOWED_GRAPHQL_ORIGINS=* in docker-compose.dev.yml" -ForegroundColor White
Write-Host ""
Write-Host "3. Test your tunnel URLs:" -ForegroundColor Yellow
Write-Host "   - Dashboard: $DashboardTunnelUrl" -ForegroundColor White
Write-Host "   - API: $ApiTunnelUrl" -ForegroundColor White
if ($StripeTunnelUrl) {
    Write-Host "   - Stripe: $StripeTunnelUrl" -ForegroundColor White
}
Write-Host ""
