#!/usr/bin/env node

/**
 * Store Initialization Script (Node.js)
 * 
 * Creates a new store configuration from the template.
 * Works cross-platform (Windows, Mac, Linux)
 * 
 * Usage:
 *   node init-store.mjs
 *   node init-store.mjs --name "My Store" --type physical --color "#FF4500"
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import readline from 'readline';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ANSI colors
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  magenta: '\x1b[35m',
  cyan: '\x1b[36m',
};

function colorize(text, color) {
  return `${colors[color]}${text}${colors.reset}`;
}

function showBanner() {
  console.log(colorize(`
 ███████╗ █████╗ ██╗     ███████╗ ██████╗ ██████╗ 
 ██╔════╝██╔══██╗██║     ██╔════╝██╔═══██╗██╔══██╗
 ███████╗███████║██║     █████╗  ██║   ██║██████╔╝
 ╚════██║██╔══██║██║     ██╔══╝  ██║   ██║██╔══██╗
 ███████║██║  ██║███████╗███████╗╚██████╔╝██║  ██║
 ╚══════╝╚═╝  ╚═╝╚══════╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝

          🚀 Store Initializer
`, 'cyan'));
}

function createSlug(name) {
  return name.toLowerCase()
    .replace(/[^a-z0-9]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

function toCamelCase(slug) {
  return slug.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase());
}

async function prompt(question, defaultValue = '') {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

  return new Promise((resolve) => {
    const displayQuestion = defaultValue 
      ? `${colorize(question, 'magenta')} [${defaultValue}]: `
      : `${colorize(question, 'magenta')}: `;
    
    rl.question(displayQuestion, (answer) => {
      rl.close();
      resolve(answer.trim() || defaultValue);
    });
  });
}

async function selectOption(question, options, defaultValue) {
  console.log(colorize(`\n${question}`, 'cyan'));
  options.forEach((opt, i) => {
    const marker = opt.value === defaultValue ? colorize('●', 'green') : '○';
    console.log(`  ${marker} ${opt.value.padEnd(12)} - ${opt.description}`);
  });
  
  const answer = await prompt('Your choice', defaultValue);
  const valid = options.find(o => o.value === answer);
  
  if (!valid) {
    console.log(colorize('Invalid option. Please try again.', 'red'));
    return selectOption(question, options, defaultValue);
  }
  
  return answer;
}

function generateConfig(config) {
  const slug = createSlug(config.name);
  const camelName = toCamelCase(slug);
  
  return `/**
 * ${config.name} - Store Configuration
 * ================================
 * Generated by init-store.mjs
 * Date: ${new Date().toISOString()}
 * Store Type: ${config.type}
 */

import { createStoreConfig, StoreConfig } from '../store.config';

export const ${camelName}Config: StoreConfig = createStoreConfig('${config.type}', {
  store: {
    name: "${config.name}",
    tagline: "${config.tagline}",
    type: "${config.type}",
    description: "Welcome to ${config.name} - ${config.tagline}",
    email: "${config.email}",
    phone: "${config.phone}",
    address: {
      street: "",
      city: "",
      state: "",
      zip: "",
      country: "",
    },
  },

  branding: {
    logo: "/logo.svg",
    logoAlt: "${config.name} Logo",
    favicon: "/favicon.ico",
    
    colors: {
      primary: "${config.primaryColor}",
      secondary: "#1F2937",
      accent: "#F59E0B",
      background: "#FFFFFF",
      surface: "#F9FAFB",
      text: "#111827",
      textMuted: "#6B7280",
      success: "#059669",
      warning: "#D97706",
      error: "#DC2626",
    },
    
    typography: {
      fontHeading: "Inter",
      fontBody: "Inter",
      fontMono: "JetBrains Mono",
    },
    
    style: {
      borderRadius: "md",
      buttonStyle: "solid",
      cardShadow: "sm",
    },
  },

  seo: {
    titleTemplate: "%s | ${config.name}",
    defaultTitle: "${config.name} - ${config.tagline}",
    defaultDescription: "Shop at ${config.name}. ${config.tagline}",
    defaultImage: "/og-image.jpg",
    twitterHandle: null,
  },

  integrations: {
    analytics: {
      googleAnalyticsId: null,
      googleTagManagerId: null,
      facebookPixelId: null,
      hotjarId: null,
    },
    marketing: {
      mailchimpListId: null,
      klaviyoApiKey: null,
    },
    support: {
      intercomAppId: null,
      zendeskKey: null,
      crispWebsiteId: null,
    },
    social: {
      facebook: null,
      instagram: null,
      twitter: null,
      youtube: null,
      tiktok: null,
      pinterest: null,
    },
  },

  localization: {
    defaultLocale: "en-US",
    supportedLocales: ["en-US"],
    dateFormat: "MM/DD/YYYY",
    timeFormat: "12h",
  },
});

export default ${camelName}Config;
`;
}

function generateIndex(config) {
  const slug = createSlug(config.name);
  const camelName = toCamelCase(slug);
  
  return `/**
 * ACTIVE STORE CONFIGURATION
 * ==========================
 * Current Store: ${config.name}
 * Generated: ${new Date().toISOString()}
 */

import { ${camelName}Config } from './stores/${slug}.config';

// ============================================
// ACTIVE CONFIGURATION
// ============================================
export const storeConfig = ${camelName}Config;

// ============================================
// RE-EXPORTS
// ============================================
export {
  type StoreConfig,
  type StoreType,
  createStoreConfig,
  defaultStoreConfig,
  storeTypePresets,
  getThemeCSSVariables,
} from './store.config';

// Export examples for reference
export * from './examples';
`;
}

async function main() {
  console.clear();
  showBanner();
  
  console.log(colorize('Welcome to the Saleor Platform Store Initializer!', 'cyan'));
  console.log('This wizard will help you set up a new store configuration.\n');

  // Parse CLI arguments
  const args = process.argv.slice(2);
  const cliConfig = {};
  
  for (let i = 0; i < args.length; i += 2) {
    const key = args[i]?.replace(/^--/, '');
    const value = args[i + 1];
    if (key && value) cliConfig[key] = value;
  }

  // Collect configuration
  const config = {
    name: cliConfig.name || await prompt('Store Name', 'My Awesome Store'),
    type: cliConfig.type || await selectOption('Store Type:', [
      { value: 'physical', description: 'Traditional retail (clothing, electronics, sports)' },
      { value: 'digital', description: 'Downloadable products (software, ebooks)' },
      { value: 'food', description: 'Food & grocery (restaurants, meal kits)' },
      { value: 'services', description: 'Service businesses (consulting, bookings)' },
      { value: 'mixed', description: 'Combination of multiple types' },
    ], 'physical'),
    tagline: cliConfig.tagline || await prompt('Store Tagline', 'Your Perfect Shopping Destination'),
    primaryColor: cliConfig.color || await prompt('Primary Brand Color (hex)', '#2563EB'),
    email: cliConfig.email || await prompt('Support Email', `support@${createSlug(cliConfig.name || 'store')}.com`),
    phone: cliConfig.phone || await prompt('Support Phone', '+1 (555) 123-4567'),
  };

  // Show summary
  console.log('\n' + colorize('━'.repeat(50), 'cyan'));
  console.log(colorize('  Store Configuration Summary', 'cyan'));
  console.log(colorize('━'.repeat(50), 'cyan'));
  console.log(`  Name:     ${colorize(config.name, 'green')}`);
  console.log(`  Type:     ${colorize(config.type, 'green')}`);
  console.log(`  Tagline:  ${colorize(config.tagline, 'green')}`);
  console.log(`  Color:    ${colorize(config.primaryColor, 'green')}`);
  console.log(`  Email:    ${colorize(config.email, 'green')}`);
  console.log(`  Phone:    ${colorize(config.phone, 'green')}`);
  console.log(colorize('━'.repeat(50), 'cyan'));

  const confirm = await prompt('\nCreate store configuration? (y/n)', 'y');
  if (!confirm.toLowerCase().startsWith('y')) {
    console.log(colorize('Operation cancelled.', 'yellow'));
    process.exit(0);
  }

  // Create files
  const slug = createSlug(config.name);
  const storesDir = path.join(__dirname, '../../storefront/src/config/stores');
  const indexPath = path.join(__dirname, '../../storefront/src/config/index.ts');

  // Create stores directory
  if (!fs.existsSync(storesDir)) {
    fs.mkdirSync(storesDir, { recursive: true });
    console.log(colorize(`\n✅ Created stores directory`, 'green'));
  }

  // Write config file
  const configPath = path.join(storesDir, `${slug}.config.ts`);
  fs.writeFileSync(configPath, generateConfig(config));
  console.log(colorize(`✅ Created store configuration: ${configPath}`, 'green'));

  // Update index
  fs.writeFileSync(indexPath, generateIndex(config));
  console.log(colorize(`✅ Updated active configuration`, 'green'));

  // Success message
  console.log('\n' + colorize('━'.repeat(50), 'green'));
  console.log(colorize('  🎉 Store Configuration Complete!', 'green'));
  console.log(colorize('━'.repeat(50), 'green'));
  console.log(colorize('\nNext Steps:', 'cyan'));
  console.log(`  1. Review your config: storefront/src/config/stores/${slug}.config.ts`);
  console.log('  2. Add your logo:      storefront/public/logo.svg');
  console.log('  3. Start the server:   cd storefront && pnpm dev');
  console.log('  4. View your store:    http://localhost:3000\n');
}

main().catch(console.error);

