export interface SettingsSearchEntry {
  page: string;
  sectionId?: string;
  title: string;
  description?: string;
  keywords: string[];
  category: string;
}

export const settingsSearchIndex: SettingsSearchEntry[] = [
  {
    page: "store",
    sectionId: "store-basic",
    title: "Basic Information",
    description: "Store name, type, and description",
    keywords: ["store", "name", "tagline", "type", "description"],
    category: "Storefront",
  },
  {
    page: "store",
    sectionId: "store-contact",
    title: "Contact Information",
    description: "Support email and phone",
    keywords: ["contact", "email", "phone", "support"],
    category: "Storefront",
  },
  {
    page: "store",
    sectionId: "store-address",
    title: "Address",
    description: "Business address",
    keywords: ["address", "street", "city", "state", "zip", "country"],
    category: "Storefront",
  },
  {
    page: "store",
    sectionId: "store-localization",
    title: "Localization",
    description: "Locale, direction, and formatting",
    keywords: ["locale", "language", "direction", "rtl", "time", "date"],
    category: "Storefront",
  },
  {
    page: "store",
    sectionId: "store-dark-mode",
    title: "Dark Mode",
    description: "Dark mode behavior and colors",
    keywords: ["dark mode", "theme", "colors"],
    category: "Storefront",
  },
  {
    page: "branding",
    sectionId: "branding-identity",
    title: "Brand Identity",
    description: "Logo, favicon, and alt text",
    keywords: ["logo", "branding", "favicon", "alt"],
    category: "Branding",
  },
  {
    page: "branding",
    sectionId: "branding-colors",
    title: "Colors",
    description: "Primary, secondary, and UI colors",
    keywords: ["colors", "primary", "secondary", "accent", "background", "text"],
    category: "Branding",
  },
  {
    page: "branding",
    sectionId: "branding-typography",
    title: "Typography",
    description: "Fonts and sizes",
    keywords: ["typography", "fonts", "heading", "body"],
    category: "Branding",
  },
  {
    page: "branding",
    sectionId: "branding-style",
    title: "Style",
    description: "Border radius and button style",
    keywords: ["style", "radius", "buttons", "shadows"],
    category: "Branding",
  },
  {
    page: "header",
    sectionId: "header-banner",
    title: "Header Banner",
    description: "Announcement banner settings",
    keywords: ["header", "banner", "announcement"],
    category: "Layout",
  },
  {
    page: "header",
    sectionId: "header-layout",
    title: "Header Layout",
    description: "Logo position and store name",
    keywords: ["logo", "header", "store name"],
    category: "Layout",
  },
  {
    page: "footer",
    sectionId: "footer-content",
    title: "Footer Content",
    description: "Newsletter, social, and contact",
    keywords: ["footer", "newsletter", "social", "contact"],
    category: "Layout",
  },
  {
    page: "footer",
    sectionId: "footer-legal",
    title: "Footer Legal",
    description: "Copyright text",
    keywords: ["footer", "copyright", "legal"],
    category: "Layout",
  },
  {
    page: "features",
    sectionId: "features-customer",
    title: "Customer Features",
    description: "Wishlist, reviews, and browsing",
    keywords: ["wishlist", "reviews", "recently viewed", "compare"],
    category: "Experience",
  },
  {
    page: "features",
    sectionId: "features-checkout",
    title: "Checkout Features",
    description: "Guest and express checkout",
    keywords: ["checkout", "guest", "express", "payment"],
    category: "Experience",
  },
  {
    page: "features",
    sectionId: "features-product",
    title: "Product Features",
    description: "Downloads, subscriptions, gift cards",
    keywords: ["digital", "subscriptions", "gift cards", "bundles"],
    category: "Experience",
  },
  {
    page: "features",
    sectionId: "features-marketing",
    title: "Marketing Features",
    description: "Newsletter and promotional tools",
    keywords: ["newsletter", "promotions", "abandoned cart"],
    category: "Experience",
  },
  {
    page: "features",
    sectionId: "features-social",
    title: "Social Features",
    description: "Social login and share buttons",
    keywords: ["social", "login", "share", "instagram"],
    category: "Experience",
  },
  {
    page: "homepage",
    sectionId: "homepage-hero",
    title: "Hero Section",
    description: "Hero content and media",
    keywords: ["hero", "banner", "cta", "slides"],
    category: "Homepage",
  },
  {
    page: "homepage",
    sectionId: "homepage-products",
    title: "Product Sections",
    description: "New arrivals, best sellers, on sale",
    keywords: ["new arrivals", "best sellers", "on sale", "featured"],
    category: "Homepage",
  },
  {
    page: "homepage",
    sectionId: "homepage-additional",
    title: "Additional Sections",
    description: "Testimonials, newsletter, Instagram",
    keywords: ["testimonials", "newsletter", "instagram", "brands"],
    category: "Homepage",
  },
  {
    page: "homepage",
    sectionId: "homepage-order",
    title: "Section Order",
    description: "Reorder homepage sections",
    keywords: ["order", "reorder", "layout"],
    category: "Homepage",
  },
  {
    page: "promo-popup",
    sectionId: "promo-main",
    title: "Promotional Popup",
    description: "Enable and configure popup",
    keywords: ["popup", "promo", "promotion", "cta"],
    category: "Marketing",
  },
  {
    page: "promo-popup",
    sectionId: "promo-content",
    title: "Popup Content",
    description: "Title, body, and badge",
    keywords: ["popup", "content", "title", "badge"],
    category: "Marketing",
  },
  {
    page: "promo-popup",
    sectionId: "promo-media",
    title: "Popup Media",
    description: "Images and background",
    keywords: ["popup", "image", "background"],
    category: "Marketing",
  },
  {
    page: "promo-popup",
    sectionId: "promo-behavior",
    title: "Popup Behavior",
    description: "Delay and visibility rules",
    keywords: ["popup", "delay", "session", "exclude"],
    category: "Marketing",
  },
  {
    page: "filters",
    sectionId: "filters-main",
    title: "Filters",
    description: "Filter visibility",
    keywords: ["filters", "price", "rating", "brand", "size"],
    category: "Catalog",
  },
  {
    page: "filters",
    sectionId: "quick-filters",
    title: "Quick Filters",
    description: "Quick filter cards",
    keywords: ["quick filters", "categories", "collections", "brands"],
    category: "Catalog",
  },
  {
    page: "ui-components",
    sectionId: "ui-buttons",
    title: "Buttons",
    description: "Primary and secondary buttons",
    keywords: ["buttons", "primary", "secondary", "outline"],
    category: "UI",
  },
  {
    page: "ui-components",
    sectionId: "ui-badges",
    title: "Badges",
    description: "Sale and featured badges",
    keywords: ["badges", "sale", "new", "discount"],
    category: "UI",
  },
  {
    page: "ui-components",
    sectionId: "ui-inputs",
    title: "Form Inputs",
    description: "Input styling",
    keywords: ["inputs", "fields", "focus"],
    category: "UI",
  },
  {
    page: "ui-components",
    sectionId: "ui-product-cards",
    title: "Product Cards",
    description: "Product card layout",
    keywords: ["product cards", "quick view", "wishlist"],
    category: "UI",
  },
  {
    page: "ui-components",
    sectionId: "ui-toasts",
    title: "Toast Notifications",
    description: "Toast position and styles",
    keywords: ["toast", "notifications", "alerts"],
    category: "UI",
  },
  {
    page: "ui-components",
    sectionId: "ui-icons",
    title: "Icons",
    description: "Icon style and colors",
    keywords: ["icons", "outline", "solid"],
    category: "UI",
  },
  {
    page: "content",
    sectionId: "content-cart",
    title: "Cart Page",
    description: "Cart copy and buttons",
    keywords: ["cart", "checkout", "free shipping"],
    category: "Content",
  },
  {
    page: "content",
    sectionId: "content-product",
    title: "Product Page",
    description: "Product copy and badges",
    keywords: ["product", "reviews", "badges"],
    category: "Content",
  },
  {
    page: "content",
    sectionId: "content-account",
    title: "Account Pages",
    description: "Sign in and account text",
    keywords: ["account", "login", "signup", "profile"],
    category: "Content",
  },
  {
    page: "content",
    sectionId: "content-general",
    title: "General",
    description: "Shared text and labels",
    keywords: ["buttons", "labels", "newsletter", "search"],
    category: "Content",
  },
  {
    page: "content",
    sectionId: "content-homepage",
    title: "Homepage Sections",
    description: "Homepage text",
    keywords: ["homepage", "sections", "titles"],
    category: "Content",
  },
  {
    page: "content",
    sectionId: "content-checkout",
    title: "Checkout",
    description: "Checkout flow text",
    keywords: ["checkout", "order", "payment"],
    category: "Content",
  },
  {
    page: "content",
    sectionId: "content-filters",
    title: "Filters & Product List",
    description: "Filters and search copy",
    keywords: ["filters", "sorting", "search"],
    category: "Content",
  },
  {
    page: "content",
    sectionId: "content-product-detail",
    title: "Product Detail Page",
    description: "Product detail UI copy",
    keywords: ["product detail", "reviews", "tabs"],
    category: "Content",
  },
  {
    page: "content",
    sectionId: "content-dashboard",
    title: "Dashboard",
    description: "Account dashboard text",
    keywords: ["dashboard", "account", "orders"],
    category: "Content",
  },
  {
    page: "content",
    sectionId: "content-orders",
    title: "Orders Page",
    description: "Orders list and details",
    keywords: ["orders", "invoice", "tracking"],
    category: "Content",
  },
  {
    page: "content",
    sectionId: "content-addresses",
    title: "Addresses Page",
    description: "Address management text",
    keywords: ["addresses", "shipping", "billing"],
    category: "Content",
  },
  {
    page: "content",
    sectionId: "content-wishlist",
    title: "Wishlist Page",
    description: "Wishlist copy",
    keywords: ["wishlist", "saved"],
    category: "Content",
  },
  {
    page: "content",
    sectionId: "content-settings",
    title: "Settings Page",
    description: "Account settings text",
    keywords: ["settings", "account", "preferences"],
    category: "Content",
  },
  {
    page: "content",
    sectionId: "content-footer",
    title: "Footer",
    description: "Footer copy",
    keywords: ["footer", "links", "legal"],
    category: "Content",
  },
  {
    page: "content",
    sectionId: "content-navbar",
    title: "Navbar",
    description: "Navigation labels, search dropdown text, and mobile menu section labels (Categories, Collections, Brands, View All Products)",
    keywords: ["navbar", "menu", "navigation", "search", "view all results", "recent searches", "clear", "mobile menu", "categories", "collections", "brands"],
    category: "Content",
  },
  {
    page: "content",
    sectionId: "content-error",
    title: "Error Page",
    description: "Error messaging",
    keywords: ["error", "empty state"],
    category: "Content",
  },
  {
    page: "content",
    sectionId: "content-404",
    title: "404 Not Found Page",
    description: "404 messaging",
    keywords: ["404", "not found"],
    category: "Content",
  },
  {
    page: "pages",
    sectionId: "pages-info",
    title: "Information Pages",
    description: "About, contact, FAQ",
    keywords: ["about", "contact", "faq", "blog"],
    category: "Pages",
  },
  {
    page: "pages",
    sectionId: "pages-legal",
    title: "Legal Pages",
    description: "Privacy, terms, shipping",
    keywords: ["privacy", "terms", "returns", "shipping"],
    category: "Pages",
  },
  {
    page: "integrations",
    sectionId: "integrations-analytics",
    title: "Analytics",
    description: "Tracking IDs",
    keywords: ["analytics", "google", "facebook", "hotjar"],
    category: "Integrations",
  },
  {
    page: "integrations",
    sectionId: "integrations-marketing",
    title: "Marketing",
    description: "Email tools",
    keywords: ["mailchimp", "klaviyo"],
    category: "Integrations",
  },
  {
    page: "integrations",
    sectionId: "integrations-support",
    title: "Customer Support",
    description: "Chat tools",
    keywords: ["intercom", "zendesk", "crisp"],
    category: "Integrations",
  },
  {
    page: "integrations",
    sectionId: "integrations-social",
    title: "Social Media",
    description: "Social links",
    keywords: ["facebook", "instagram", "tiktok", "pinterest"],
    category: "Integrations",
  },
  {
    page: "seo",
    sectionId: "seo-titles",
    title: "Page Titles",
    description: "Title templates",
    keywords: ["seo", "titles", "templates"],
    category: "SEO",
  },
  {
    page: "seo",
    sectionId: "seo-description",
    title: "Meta Description",
    description: "Default description",
    keywords: ["seo", "meta", "description"],
    category: "SEO",
  },
  {
    page: "seo",
    sectionId: "seo-social",
    title: "Social Sharing",
    description: "Open Graph and Twitter",
    keywords: ["open graph", "twitter", "social"],
    category: "SEO",
  },
];
