import type { Template } from "./types";

export const BUILT_IN_TEMPLATES: Template[] = [
  // --- Product Templates ---
  {
    id: "white-bg-square",
    name: "White Background (Square)",
    description: "Clean white background, perfect for e-commerce catalogs",
    category: "product",
    width: 1024,
    height: 1024,
    backgroundColor: "#ffffff",
    layers: [
      {
        type: "rect",
        left: 0, top: 0, width: 1024, height: 1024,
        fill: "#ffffff",
      },
      {
        type: "image",
        placeholder: "Product Image",
        left: 112, top: 62, width: 800, height: 800,
      },
      {
        type: "text",
        text: "Product Name",
        left: 112, top: 890, width: 800, height: 40,
        fontSize: 28, fontFamily: "Arial", fontWeight: "bold",
        fill: "#1a1a1a", textAlign: "center",
      },
      {
        type: "text",
        text: "$99.00",
        left: 112, top: 935, width: 800, height: 32,
        fontSize: 22, fontFamily: "Arial",
        fill: "#666666", textAlign: "center",
      },
    ],
  },
  {
    id: "white-bg-portrait",
    name: "White Background (Portrait)",
    description: "Tall white background for fashion and apparel",
    category: "product",
    width: 800,
    height: 1200,
    backgroundColor: "#ffffff",
    layers: [
      {
        type: "image",
        placeholder: "Product Image",
        left: 50, top: 50, width: 700, height: 950,
      },
      {
        type: "text",
        text: "Product Name",
        left: 50, top: 1030, width: 700, height: 40,
        fontSize: 26, fontFamily: "Arial", fontWeight: "bold",
        fill: "#1a1a1a", textAlign: "center",
      },
      {
        type: "text",
        text: "$99.00",
        left: 50, top: 1080, width: 700, height: 30,
        fontSize: 20, fontFamily: "Arial",
        fill: "#666666", textAlign: "center",
      },
    ],
  },
  {
    id: "gradient-product",
    name: "Gradient Product Card",
    description: "Subtle gradient background with product showcase",
    category: "product",
    width: 1024,
    height: 1024,
    backgroundColor: "#f8f9fa",
    layers: [
      {
        type: "rect",
        left: 0, top: 0, width: 1024, height: 1024,
        fill: "#f0f0f0",
      },
      {
        type: "rect",
        left: 0, top: 780, width: 1024, height: 244,
        fill: "#1a1a1a",
      },
      {
        type: "image",
        placeholder: "Product Image",
        left: 162, top: 50, width: 700, height: 700,
      },
      {
        type: "text",
        text: "Product Name",
        left: 40, top: 810, width: 944, height: 40,
        fontSize: 30, fontFamily: "Arial", fontWeight: "bold",
        fill: "#ffffff", textAlign: "left",
      },
      {
        type: "text",
        text: "$99.00",
        left: 40, top: 860, width: 944, height: 30,
        fontSize: 24, fontFamily: "Arial",
        fill: "#cccccc", textAlign: "left",
      },
    ],
  },

  // --- Social Media Templates ---
  {
    id: "instagram-square",
    name: "Instagram Post",
    description: "1080x1080 square post for Instagram",
    category: "social",
    width: 1080,
    height: 1080,
    backgroundColor: "#ffffff",
    layers: [
      {
        type: "image",
        placeholder: "Product Image",
        left: 40, top: 40, width: 1000, height: 750,
      },
      {
        type: "rect",
        left: 0, top: 810, width: 1080, height: 270,
        fill: "#000000", opacity: 0.85,
      },
      {
        type: "text",
        text: "NEW ARRIVAL",
        left: 40, top: 830, width: 1000, height: 36,
        fontSize: 14, fontFamily: "Arial",
        fill: "#888888", textAlign: "left",
      },
      {
        type: "text",
        text: "Product Name Here",
        left: 40, top: 870, width: 1000, height: 50,
        fontSize: 36, fontFamily: "Arial", fontWeight: "bold",
        fill: "#ffffff", textAlign: "left",
      },
      {
        type: "text",
        text: "Shop Now",
        left: 40, top: 950, width: 200, height: 44,
        fontSize: 16, fontFamily: "Arial", fontWeight: "bold",
        fill: "#ffffff", textAlign: "center",
      },
    ],
  },
  {
    id: "instagram-story",
    name: "Instagram Story",
    description: "1080x1920 vertical story format",
    category: "social",
    width: 1080,
    height: 1920,
    backgroundColor: "#111111",
    layers: [
      {
        type: "image",
        placeholder: "Product Image",
        left: 40, top: 200, width: 1000, height: 1000,
      },
      {
        type: "text",
        text: "SALE",
        left: 40, top: 80, width: 1000, height: 70,
        fontSize: 56, fontFamily: "Arial", fontWeight: "bold",
        fill: "#ff4444", textAlign: "center",
      },
      {
        type: "text",
        text: "Up to 50% Off",
        left: 40, top: 1280, width: 1000, height: 50,
        fontSize: 32, fontFamily: "Arial",
        fill: "#ffffff", textAlign: "center",
      },
      {
        type: "text",
        text: "SHOP NOW",
        left: 340, top: 1400, width: 400, height: 56,
        fontSize: 20, fontFamily: "Arial", fontWeight: "bold",
        fill: "#ffffff", textAlign: "center",
      },
    ],
  },
  {
    id: "facebook-cover",
    name: "Facebook Cover",
    description: "820x312 cover photo with product showcase",
    category: "social",
    width: 820,
    height: 312,
    backgroundColor: "#1a1a2e",
    layers: [
      {
        type: "image",
        placeholder: "Product Image",
        left: 520, top: 20, width: 270, height: 270,
      },
      {
        type: "text",
        text: "Brand Name",
        left: 40, top: 60, width: 460, height: 50,
        fontSize: 38, fontFamily: "Arial", fontWeight: "bold",
        fill: "#ffffff", textAlign: "left",
      },
      {
        type: "text",
        text: "New Collection Available",
        left: 40, top: 120, width: 460, height: 30,
        fontSize: 18, fontFamily: "Arial",
        fill: "#aaaaaa", textAlign: "left",
      },
      {
        type: "text",
        text: "www.yourstore.com",
        left: 40, top: 220, width: 460, height: 28,
        fontSize: 14, fontFamily: "Arial",
        fill: "#666666", textAlign: "left",
      },
    ],
  },

  // --- Banner Templates ---
  {
    id: "hero-banner",
    name: "Hero Banner",
    description: "1440x480 wide hero banner for your storefront",
    category: "banner",
    width: 1440,
    height: 480,
    backgroundColor: "#f5f5f5",
    layers: [
      {
        type: "image",
        placeholder: "Product Image",
        left: 900, top: 20, width: 500, height: 440,
      },
      {
        type: "text",
        text: "SUMMER COLLECTION",
        left: 60, top: 80, width: 800, height: 60,
        fontSize: 48, fontFamily: "Arial", fontWeight: "bold",
        fill: "#1a1a1a", textAlign: "left",
      },
      {
        type: "text",
        text: "Discover the latest styles for the season",
        left: 60, top: 160, width: 800, height: 36,
        fontSize: 20, fontFamily: "Arial",
        fill: "#666666", textAlign: "left",
      },
      {
        type: "rect",
        left: 60, top: 240, width: 200, height: 50,
        fill: "#1a1a1a",
      },
      {
        type: "text",
        text: "Shop Now",
        left: 60, top: 250, width: 200, height: 32,
        fontSize: 16, fontFamily: "Arial", fontWeight: "bold",
        fill: "#ffffff", textAlign: "center",
      },
    ],
  },
  {
    id: "promo-banner",
    name: "Promo Banner",
    description: "1200x400 promotional banner with sale messaging",
    category: "banner",
    width: 1200,
    height: 400,
    backgroundColor: "#ff4444",
    layers: [
      {
        type: "text",
        text: "FLASH SALE",
        left: 40, top: 40, width: 600, height: 80,
        fontSize: 64, fontFamily: "Arial", fontWeight: "bold",
        fill: "#ffffff", textAlign: "left",
      },
      {
        type: "text",
        text: "50% OFF",
        left: 40, top: 140, width: 600, height: 60,
        fontSize: 48, fontFamily: "Arial", fontWeight: "bold",
        fill: "#ffdddd", textAlign: "left",
      },
      {
        type: "text",
        text: "Limited time only. Use code: FLASH50",
        left: 40, top: 220, width: 600, height: 30,
        fontSize: 18, fontFamily: "Arial",
        fill: "#ffffff", textAlign: "left",
      },
      {
        type: "image",
        placeholder: "Product Image",
        left: 780, top: 30, width: 380, height: 340,
      },
    ],
  },

  // --- Lifestyle Templates ---
  {
    id: "lifestyle-minimal",
    name: "Minimal Lifestyle",
    description: "Clean, minimal layout with subtle styling",
    category: "lifestyle",
    width: 1024,
    height: 1024,
    backgroundColor: "#fafaf9",
    layers: [
      {
        type: "image",
        placeholder: "Product Image",
        left: 112, top: 80, width: 800, height: 700,
      },
      {
        type: "text",
        text: "HANDCRAFTED",
        left: 112, top: 820, width: 800, height: 24,
        fontSize: 12, fontFamily: "Arial",
        fill: "#999999", textAlign: "center",
      },
      {
        type: "text",
        text: "Premium Collection",
        left: 112, top: 854, width: 800, height: 50,
        fontSize: 32, fontFamily: "Georgia", fontWeight: "bold",
        fill: "#2c2c2c", textAlign: "center",
      },
      {
        type: "text",
        text: "Designed with care, built to last.",
        left: 112, top: 916, width: 800, height: 30,
        fontSize: 16, fontFamily: "Georgia",
        fill: "#888888", textAlign: "center",
      },
    ],
  },
  {
    id: "lifestyle-bold",
    name: "Bold Lifestyle",
    description: "High-contrast bold layout with dark theme",
    category: "lifestyle",
    width: 1024,
    height: 1024,
    backgroundColor: "#1a1a1a",
    layers: [
      {
        type: "image",
        placeholder: "Product Image",
        left: 262, top: 62, width: 500, height: 500,
      },
      {
        type: "text",
        text: "ELEVATE",
        left: 0, top: 600, width: 1024, height: 80,
        fontSize: 72, fontFamily: "Arial", fontWeight: "bold",
        fill: "#ffffff", textAlign: "center",
      },
      {
        type: "text",
        text: "YOUR STYLE",
        left: 0, top: 690, width: 1024, height: 60,
        fontSize: 48, fontFamily: "Arial",
        fill: "#666666", textAlign: "center",
      },
      {
        type: "rect",
        left: 362, top: 800, width: 300, height: 50,
        fill: "#ffffff",
      },
      {
        type: "text",
        text: "DISCOVER",
        left: 362, top: 810, width: 300, height: 30,
        fontSize: 18, fontFamily: "Arial", fontWeight: "bold",
        fill: "#1a1a1a", textAlign: "center",
      },
    ],
  },
  {
    id: "lifestyle-earth",
    name: "Earth Tones",
    description: "Warm earth-toned layout for natural products",
    category: "lifestyle",
    width: 1024,
    height: 1024,
    backgroundColor: "#e8ddd3",
    layers: [
      {
        type: "image",
        placeholder: "Product Image",
        left: 50, top: 50, width: 600, height: 600,
      },
      {
        type: "rect",
        left: 550, top: 500, width: 440, height: 440,
        fill: "#c4a882",
      },
      {
        type: "text",
        text: "Natural",
        left: 580, top: 560, width: 380, height: 50,
        fontSize: 40, fontFamily: "Georgia", fontWeight: "bold",
        fill: "#ffffff", textAlign: "left",
      },
      {
        type: "text",
        text: "Comfort",
        left: 580, top: 620, width: 380, height: 50,
        fontSize: 40, fontFamily: "Georgia",
        fill: "#ffffff", textAlign: "left",
      },
      {
        type: "text",
        text: "Made with sustainable materials",
        left: 580, top: 700, width: 380, height: 24,
        fontSize: 14, fontFamily: "Arial",
        fill: "#ffffff", textAlign: "left",
        opacity: 0.8,
      },
    ],
  },
  {
    id: "product-comparison",
    name: "Product Comparison",
    description: "Side-by-side product comparison layout",
    category: "product",
    width: 1200,
    height: 800,
    backgroundColor: "#ffffff",
    isMockup: true,
    layers: [
      {
        type: "image",
        placeholder: "Product Image 1",
        placeholderType: "product-image",
        left: 50, top: 50, width: 500, height: 500,
      },
      {
        type: "image",
        placeholder: "Product Image 2",
        left: 650, top: 50, width: 500, height: 500,
      },
      {
        type: "text",
        text: "VS",
        left: 550, top: 250, width: 100, height: 50,
        fontSize: 36, fontFamily: "Arial", fontWeight: "bold",
        fill: "#cccccc", textAlign: "center",
      },
      {
        type: "text",
        text: "Product A — $99",
        placeholderType: "product-name",
        left: 50, top: 580, width: 500, height: 36,
        fontSize: 22, fontFamily: "Arial", fontWeight: "bold",
        fill: "#1a1a1a", textAlign: "center",
      },
      {
        type: "text",
        text: "Product B — $129",
        left: 650, top: 580, width: 500, height: 36,
        fontSize: 22, fontFamily: "Arial", fontWeight: "bold",
        fill: "#1a1a1a", textAlign: "center",
      },
    ],
  },

  // --- Mockup Templates ---
  {
    id: "product-showcase",
    name: "Product Showcase",
    description: "Product mockup with image, name, and price placeholders",
    category: "product",
    isMockup: true,
    width: 1080,
    height: 1080,
    backgroundColor: "#f5f5f5",
    layers: [
      {
        type: "rect",
        left: 0, top: 0, width: 1080, height: 1080,
        fill: "#f5f5f5",
      },
      {
        type: "image",
        placeholder: "Product Image",
        placeholderType: "product-image",
        left: 190, top: 80, width: 700, height: 700,
      },
      {
        type: "text",
        text: "Product Name",
        placeholder: "Product Name",
        placeholderType: "product-name",
        left: 60, top: 830, width: 700, height: 40,
        fontSize: 32, fontFamily: "Arial", fontWeight: "bold",
        fill: "#1a1a1a", textAlign: "left",
      },
      {
        type: "text",
        text: "$99.00",
        placeholder: "Price",
        placeholderType: "product-price",
        left: 60, top: 885, width: 300, height: 32,
        fontSize: 24, fontFamily: "Arial",
        fill: "#666666", textAlign: "left",
      },
      {
        type: "text",
        text: "Product description goes here",
        placeholder: "Description",
        placeholderType: "product-description",
        left: 60, top: 935, width: 960, height: 80,
        fontSize: 16, fontFamily: "Arial",
        fill: "#999999", textAlign: "left",
      },
    ],
  },
  {
    id: "product-lifestyle-mockup",
    name: "Product Lifestyle",
    description: "Product with lifestyle context — image left, details right",
    category: "lifestyle",
    isMockup: true,
    width: 1200,
    height: 800,
    backgroundColor: "#faf8f5",
    layers: [
      {
        type: "rect",
        left: 0, top: 0, width: 1200, height: 800,
        fill: "#faf8f5",
      },
      {
        type: "image",
        placeholder: "Product Image",
        placeholderType: "product-image",
        left: 40, top: 40, width: 560, height: 720,
      },
      {
        type: "text",
        text: "Product Name",
        placeholder: "Product Name",
        placeholderType: "product-name",
        left: 660, top: 120, width: 480, height: 48,
        fontSize: 36, fontFamily: "Georgia", fontWeight: "bold",
        fill: "#2c2c2c", textAlign: "left",
      },
      {
        type: "text",
        text: "A brief product description with key features and benefits.",
        placeholder: "Description",
        placeholderType: "product-description",
        left: 660, top: 200, width: 480, height: 120,
        fontSize: 16, fontFamily: "Arial",
        fill: "#666666", textAlign: "left",
      },
      {
        type: "rect",
        left: 660, top: 360, width: 160, height: 48,
        fill: "#2c2c2c",
      },
      {
        type: "text",
        text: "$99.00",
        placeholder: "Price",
        placeholderType: "product-price",
        left: 670, top: 368, width: 140, height: 32,
        fontSize: 22, fontFamily: "Arial", fontWeight: "bold",
        fill: "#ffffff", textAlign: "center",
      },
    ],
  },
];
