/**
 * Converts camelCase field names to human-readable Title Case labels.
 * e.g. "freeShippingThreshold" → "Free Shipping Threshold"
 */
export function camelCaseToTitleCase(str: string): string {
  // Handle common abbreviations
  const withSpaces = str
    .replace(/([A-Z]{2,})/g, " $1") // consecutive caps like "URL" → " URL"
    .replace(/([a-z])([A-Z])/g, "$1 $2") // camelCase boundary
    .replace(/([A-Z])([A-Z][a-z])/g, "$1 $2") // ABc → A Bc
    .replace(/^./, (c) => c.toUpperCase()) // capitalize first
    .trim();

  // Capitalize each word
  return withSpaces
    .split(" ")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

/**
 * Returns the last segment of a dot-path as a Title Case label.
 * e.g. "content.cart.cartTitle" → "Cart Title"
 */
export function pathToLabel(fieldPath: string): string {
  const segments = fieldPath.split(".");
  const lastSegment = segments[segments.length - 1];
  if (!lastSegment) return fieldPath;

  // Check override first
  const override = FIELD_LABELS[fieldPath];
  if (override) return override;

  return camelCaseToTitleCase(lastSegment);
}

/**
 * Manual label overrides for fields where camelCase conversion produces poor results.
 * Key: full config path, Value: human-readable label
 */
const FIELD_LABELS: Record<string, string> = {
  // Store
  "store.name": "Store Name",
  "store.email": "Support Email",
  "store.phone": "Support Phone",

  // Branding
  "branding.logo": "Logo URL",
  "branding.logoAlt": "Logo Alt Text",
  "branding.favicon": "Favicon URL",
  "branding.colors.textMuted": "Muted Text Color",
  "branding.typography.fontHeading": "Heading Font Family",
  "branding.typography.fontBody": "Body Font Family",
  "branding.typography.fontMono": "Monospace Font Family",
  "branding.style.borderRadius": "Global Border Radius",
  "branding.style.buttonStyle": "Default Button Style",
  "branding.style.cardShadow": "Default Card Shadow",

  // Features
  "features.compareProducts": "Compare Products",
  "features.productReviews": "Product Reviews",
  "features.recentlyViewed": "Recently Viewed Products",
  "features.scrollToTop": "Scroll to Top Button",
  "features.guestCheckout": "Guest Checkout",
  "features.expressCheckout": "Express Checkout",
  "features.savePaymentMethods": "Save Payment Methods",
  "features.digitalDownloads": "Digital Downloads",
  "features.productBundles": "Product Bundles",
  "features.giftCards": "Gift Cards",
  "features.promotionalBanners": "Promotional Banners",
  "features.abandonedCartEmails": "Abandoned Cart Emails",
  "features.socialLogin": "Social Login",
  "features.shareButtons": "Share Buttons",
  "features.instagramFeed": "Instagram Feed",
  "features.relatedProducts": "Related Products",

  // Ecommerce
  "ecommerce.shipping.freeShippingThreshold": "Free Shipping Threshold",
  "ecommerce.shipping.showEstimatedDelivery": "Show Estimated Delivery",
  "ecommerce.shipping.defaultEstimatedMinDays": "Default Estimated Min Days",
  "ecommerce.shipping.defaultEstimatedMaxDays": "Default Estimated Max Days",
  "ecommerce.shipping.estimatedDeliveryFormat": "Estimated Delivery Format",
  "ecommerce.shipping.freeShippingRule.enabled": "Enable Free Shipping Rule",
  "ecommerce.shipping.freeShippingRule.cartMinimum": "Free Rule Cart Minimum",
  "ecommerce.shipping.freeShippingRule.maxMethodPrice": "Free Rule Max Method Price",
  "ecommerce.shipping.freeShippingRule.methodNameFilter": "Free Rule Method Name Filter",
  "ecommerce.shipping.discountRule.enabled": "Enable Shipping Discount Rule",
  "ecommerce.shipping.discountRule.cartMinimum": "Discount Rule Cart Minimum",
  "ecommerce.shipping.discountRule.type": "Shipping Discount Type",
  "ecommerce.shipping.discountRule.value": "Shipping Discount Value",
  "ecommerce.shipping.discountRule.maxMethodPrice": "Discount Rule Max Method Price",
  "ecommerce.shipping.discountRule.minPrice": "Shipping Discount Floor Price",
  "ecommerce.shipping.discountRule.methodNameFilter": "Discount Rule Method Name Filter",
  "ecommerce.shipping.showOriginalPrice": "Show Original Shipping Price",
  "ecommerce.shipping.dropship.marginProtectionEnabled": "Enable Dropship Margin Protection",
  "ecommerce.shipping.dropship.marginThreshold": "Minimum Profit Margin (%)",
  "ecommerce.shipping.dropship.trackOriginalPrices": "Track Original Shipping Prices",
  "ecommerce.tax.showPricesWithTax": "Show Prices With Tax",
  "ecommerce.tax.taxIncludedInPrice": "Tax Included In Price",
  "ecommerce.inventory.showStockLevel": "Show Stock Level",
  "ecommerce.inventory.lowStockThreshold": "Low Stock Threshold",
  "ecommerce.inventory.allowBackorders": "Allow Backorders",
  "ecommerce.checkout.minOrderAmount": "Minimum Order Amount",
  "ecommerce.checkout.maxOrderAmount": "Maximum Order Amount",
  "ecommerce.checkout.termsRequired": "Terms Required at Checkout",

  // SEO
  "seo.titleTemplate": "SEO Title Template",
  "seo.defaultTitle": "Default Page Title",
  "seo.defaultDescription": "Default Meta Description",
  "seo.defaultImage": "Default OG Image URL",
  "seo.twitterHandle": "Twitter Handle",

  // Localization
  "localization.defaultLocale": "Default Locale",
  "localization.supportedLocales": "Supported Locales",
  "localization.dateFormat": "Date Format",
  "localization.timeFormat": "Time Format",
  "localization.direction": "Text Direction (LTR/RTL)",
  "localization.rtlLocales": "RTL Locale Codes",
  "localization.drawerSideOverride": "Drawer Side Override",

  // Dark Mode
  "darkMode.enabled": "Enable Dark Mode",
  "darkMode.auto": "Auto Dark Mode (System)",

  // Homepage sections
  "homepage.sections.hero.ctaText": "Hero CTA Button Text",
  "homepage.sections.hero.ctaLink": "Hero CTA Button Link",
  "homepage.sections.hero.overlayOpacity": "Hero Overlay Opacity",
  "homepage.sections.hero.autoRotateSeconds": "Hero Auto Rotate Interval",
  "homepage.sections.hero.showProgressBar": "Show Hero Progress Bar",
  "homepage.sections.hero.showNavDots": "Show Hero Navigation Dots",

  // UI Components
  "ui.buttons.borderRadius": "Button Border Radius",
  "ui.badges.sale.borderRadius": "Sale Badge Border Radius",
  "ui.inputs.borderRadius": "Input Border Radius",
  "ui.inputs.focusBorderColor": "Input Focus Border Color",
  "ui.inputs.focusRingColor": "Input Focus Ring Color",
  "ui.productCard.showQuickView": "Show Quick View Button",
  "ui.productCard.showWishlistButton": "Show Wishlist Button on Card",
  "ui.productCard.showAddToCart": "Show Add to Cart on Card",
  "ui.productCard.imageAspectRatio": "Product Card Image Aspect Ratio",
  "ui.productCard.hoverEffect": "Product Card Hover Effect",
  "ui.productCard.badgePosition": "Product Card Badge Position",
  "ui.productCard.imageFit": "Product Card Image Fit",
  "ui.productCard.showPrice": "Show Price on Product Cards",
  "ui.productCard.showOriginalPrice": "Show Original Price on Product Cards",
  "ui.productCard.showCategory": "Show Category Label on Product Cards",
  "ui.productCard.showDeliveryEstimate": "Show Delivery Estimate on Product Cards",
  "ui.productCard.showShareButton": "Show Share Button on Product Cards",
  "ui.productCard.showDiscountBadge": "Show Discount Badge on Product Cards",
  "ui.productCard.showOutOfStockBadge": "Show Out of Stock Badge on Product Cards",
  "ui.productCard.showLowStockBadge": "Show Low Stock Badge on Product Cards",
  "ui.productCard.showNewBadge": "Show New Badge on Product Cards",
  "ui.productCard.titleMaxLines": "Product Card Title Max Lines",
  "ui.productCard.contentAlignment": "Product Card Content Alignment",

  // Per-location card overrides
  "cardOverrides.plp": "PLP Product Card Overrides",
  "cardOverrides.relatedProducts": "Related Products Card Overrides",
  "cardOverrides.recentlyViewed": "Recently Viewed Card Overrides",
  "cardOverrides.wishlistDrawer": "Wishlist Drawer Card Overrides",
  "cardOverrides.productGrid": "Product Grid Card Overrides",
  "ui.productCard.textStyles.name.fontSize": "Product Name Font Size",
  "ui.productCard.textStyles.name.fontWeight": "Product Name Font Weight",
  "ui.productCard.textStyles.name.color": "Product Name Color",
  "ui.productCard.textStyles.price.fontSize": "Price Font Size",
  "ui.productCard.textStyles.price.fontWeight": "Price Font Weight",
  "ui.productCard.textStyles.price.color": "Price Color",
  "ui.productCard.textStyles.originalPrice.fontSize": "Original Price Font Size",
  "ui.productCard.textStyles.originalPrice.fontWeight": "Original Price Font Weight",
  "ui.productCard.textStyles.originalPrice.color": "Original Price Color",
  "ui.productCard.textStyles.reviewCount.fontSize": "Review Count Font Size",
  "ui.productCard.textStyles.reviewCount.fontWeight": "Review Count Font Weight",
  "ui.productCard.textStyles.reviewCount.color": "Review Count Color",
  "ui.toasts.position": "Toast Notification Position",
  "ui.icons.style": "Icon Style",
  "ui.icons.defaultColor": "Default Icon Color",
  "ui.icons.activeColor": "Active Icon Color",
  "ui.cart.displayMode": "Cart Display Mode",
  "ui.cart.drawerSide": "Cart Drawer Side",
  "ui.cart.showDeleteText": "Show Delete Text on Cart Items",
  "ui.cart.showSaveForLater": "Show Save For Later",

  // Promo Popup
  "promoPopup.enabled": "Enable Promo Popup",
  "promoPopup.delaySeconds": "Popup Delay (Seconds)",
  "promoPopup.showOncePerSession": "Show Once Per Session",
  "promoPopup.excludeCheckout": "Exclude From Checkout",
  "promoPopup.excludeCart": "Exclude From Cart",
  "promoPopup.autoDetectSales": "Auto Detect Sales",
  "promoPopup.ttlHours": "Popup TTL (Hours)",
  "promoPopup.ctaText": "Popup CTA Button Text",
  "promoPopup.ctaLink": "Popup CTA Button Link",
  "promoPopup.imageUrl": "Popup Image URL",
  "promoPopup.backgroundImageUrl": "Popup Background Image URL",

  // Integrations
  "integrations.analytics.googleAnalyticsId": "Google Analytics ID",
  "integrations.analytics.googleTagManagerId": "Google Tag Manager ID",
  "integrations.analytics.facebookPixelId": "Facebook Pixel ID",
  "integrations.analytics.hotjarId": "Hotjar ID",
  "integrations.marketing.mailchimpListId": "Mailchimp List ID",
  "integrations.marketing.klaviyoApiKey": "Klaviyo API Key",
  "integrations.support.intercomAppId": "Intercom App ID",
  "integrations.support.zendeskKey": "Zendesk Key",
  "integrations.support.crispWebsiteId": "Crisp Website ID",

  // Related Products
  "relatedProducts.enabled": "Enable Related Products",
  "relatedProducts.strategy": "Related Products Strategy",
  "relatedProducts.maxItems": "Max Related Products",
  "relatedProducts.showOnMobile": "Show Related on Mobile",
  "relatedProducts.title": "Related Products Title",
  "relatedProducts.subtitle": "Related Products Subtitle",

  // Filters
  "filters.enabled": "Enable Filters",
  "filters.priceFilter.enabled": "Enable Price Filter",
  "filters.priceFilter.showQuickButtons": "Show Price Quick Buttons",
  "quickFilters.enabled": "Enable Quick Filters",
  "quickFilters.showCategories": "Show Category Quick Filters",
  "quickFilters.showCollections": "Show Collection Quick Filters",
  "quickFilters.showBrands": "Show Brand Quick Filters",
  "quickFilters.categoryLimit": "Quick Filter Category Limit",
  "quickFilters.collectionLimit": "Quick Filter Collection Limit",
  "quickFilters.brandLimit": "Quick Filter Brand Limit",

  // Design tokens — status colors
  "design.statusColors.success": "Success Status Color",
  "design.statusColors.warning": "Warning Status Color",
  "design.statusColors.error": "Error Status Color",
  "design.statusColors.info": "Info Status Color",

  // Design tokens — grid
  "design.grid.productColumns.sm": "Product Columns (Small Screens)",
  "design.grid.productColumns.md": "Product Columns (Medium Screens)",
  "design.grid.productColumns.lg": "Product Columns (Large Screens)",
  "design.grid.productColumns.xl": "Product Columns (Extra Large Screens)",
  "design.grid.productGap": "Product Grid Gap",

  // Design tokens — animation timings
  "design.animations.carouselCycleSeconds": "Carousel Cycle Duration (seconds)",
  "design.animations.toastDurationMs": "Toast Auto-Dismiss Duration (ms)",

  // Checkout UI
  "checkoutUi.accordion.completedStepColor": "Checkout Completed Step Color",
  "checkoutUi.accordion.activeStepColor": "Checkout Active Step Color",
  "checkoutUi.confirmation.showTimeline": "Show Order Timeline",
  "checkoutUi.confirmation.showPrintReceipt": "Show Print Receipt Button",
  "checkoutUi.progressBar.completedColor": "Progress Bar Completed Color",
  "checkoutUi.progressBar.activeColor": "Progress Bar Active Color",

  // ── Cart Text ──
  "content.cart.emptyCartTitle": "Empty Cart Title",
  "content.cart.emptyCartMessage": "Empty Cart Message",
  "content.cart.checkoutButton": "Checkout Button Text",
  "content.cart.continueShoppingButton": "Continue Shopping Button",
  "content.cart.freeShippingMessage": "Free Shipping Message",
  "content.cart.cartTitle": "Cart Title",
  "content.cart.selectAllButton": "Select All Button",
  "content.cart.deselectAllButton": "Deselect All Button",
  "content.cart.selectAllItemsButton": "Select All Items Button",
  "content.cart.selectItemsToCheckout": "Select Items to Checkout Text",
  "content.cart.freeShippingThresholdReached": "Free Shipping Threshold Reached Text",
  "content.cart.addXMoreForFreeShipping": "Add X More For Free Shipping Text",
  "content.cart.unlockedFreeShipping": "Unlocked Free Shipping Text",
  "content.cart.freeShippingSelectMethods": "Cart Free Shipping Select Methods",
  "content.cart.saveForLaterButton": "Save For Later Button",
  "content.cart.moveToCartButton": "Move to Cart Button",
  "content.cart.deleteButton": "Cart Delete Button",
  "content.cart.removeButton": "Cart Remove Button",
  "content.cart.removingText": "Cart Removing Text",
  "content.cart.itemSingular": "Item Singular Label",
  "content.cart.itemPlural": "Items Plural Label",
  "content.cart.orderSummaryTitle": "Cart Order Summary Title",
  "content.cart.itemsSelectedText": "Items Selected Text",
  "content.cart.eachLabel": "Each Label",
  "content.cart.availableLabel": "Available Label",
  "content.cart.outOfStockLabel": "Out of Stock Label",
  "content.cart.loadingCheckoutTitle": "Loading Checkout Title",
  "content.cart.loadingCheckoutMessage": "Loading Checkout Message",
  "content.cart.quantityMinError": "Quantity Min Error",
  "content.cart.onlyXItemsAvailable": "Only X Items Available Error",
  "content.cart.useDeleteButtonMessage": "Use Delete Button Message",
  "content.cart.failedToUpdateQuantity": "Failed to Update Quantity Error",
  "content.cart.onlyXAvailable": "Only X Available Error",
  "content.cart.quantityUpdatedSuccess": "Quantity Updated Success Message",
  "content.cart.promoCodeLabel": "Cart Promo Code Label",
  "content.cart.promoCodePlaceholder": "Cart Promo Code Placeholder",
  "content.cart.promoCodeApplyButton": "Cart Promo Code Apply Button",
  "content.cart.eligibleForFreeShipping": "Eligible For Free Shipping Text",
  "content.cart.subtotalLabel": "Cart Subtotal Label",
  "content.cart.subtotalLabelWithCount": "Subtotal With Count Label",
  "content.cart.shippingLabel": "Cart Shipping Label",
  "content.cart.shippingFree": "Cart Shipping Free Label",
  "content.cart.shippingCalculatedAtCheckout": "Shipping Calculated At Checkout",
  "content.cart.totalLabel": "Cart Total Label",
  "content.cart.selectItemsButton": "Select Items Button",
  "content.cart.preparingCheckout": "Preparing Checkout Text",
  "content.cart.loadingCheckout": "Loading Checkout Text",
  "content.cart.originalSubtotalLabel": "Original Subtotal Label",
  "content.cart.discountedSubtotalLabel": "Discounted Subtotal Label",
  "content.cart.secureCheckoutText": "Secure Checkout Text",
  "content.cart.sslEncryptedText": "SSL Encrypted Text",
  "content.cart.acceptedPaymentMethods": "Accepted Payment Methods Text",
  "content.cart.providedByStripe": "Provided By Stripe Text",
  "content.cart.itemsSavedForLater": "Items Saved For Later Text",
  "content.cart.viewCartButton": "View Cart Button",
  "content.cart.shippingNote": "Shipping Note Text",
  "content.cart.youSaveLabel": "You Save Label",
  "content.cart.giftLabel": "Gift Label",
  "content.cart.giftAddedMessage": "Gift Added Message",
  "content.cart.giftRemoveHint": "Gift Remove Hint",
  "content.cart.deliverySummaryLabel": "Delivery Summary Label",
  "content.cart.promoCodeVoucherNotApplicableError": "Cart Voucher Not Applicable Error",
  "content.cart.promoCodeGiftCardNotApplicableError": "Cart Gift Card Not Applicable Error",
  "content.cart.promoCodeNotFoundError": "Cart Promo Code Not Found Error",
  "content.cart.promoCodeInvalidError": "Cart Promo Code Invalid Error",
  "content.cart.promoCodeGenericError": "Cart Promo Code Generic Error",
  "content.cart.promoCodeAppliedSuccess": "Cart Promo Code Applied Success",
  "content.cart.promoCodeRemovedSuccess": "Cart Promo Code Removed Success",
  "content.cart.promoCodeRemoveError": "Cart Promo Code Remove Error",

  // ── Product Text ──
  "content.product.addToCartButton": "Add to Cart Button Text",
  "content.product.buyNowButton": "Buy Now Button Text",
  "content.product.outOfStockText": "Out of Stock Text",
  "content.product.lowStockText": "Low Stock Text",
  "content.product.inStockText": "In Stock Text",
  "content.product.saleBadgeText": "Sale Badge Text",
  "content.product.newBadgeText": "New Badge Text",
  "content.product.reviewsTitle": "Reviews Title",
  "content.product.writeReviewButton": "Write Review Button",
  "content.product.noReviewsText": "No Reviews Text",
  "content.product.addingButton": "Adding Button Text",
  "content.product.addedToCartButton": "Added to Cart Button",
  "content.product.selectOptionsButton": "Select Options Button",
  "content.product.viewCartLink": "View Cart Link",
  "content.product.quickAddButton": "Quick Add Button",
  "content.product.viewFullPageLink": "View Full Page Link",
  "content.product.loadingProductText": "Loading Product Text",
  "content.product.productDetailsTitle": "Product Details Title",
  "content.product.closeButton": "Close Button",
  "content.product.productNotFoundText": "Product Not Found Text",
  "content.product.errorLoadingProductText": "Error Loading Product Text",

  // ── Account Text ──
  "content.account.signInTitle": "Sign In Title",
  "content.account.signUpTitle": "Sign Up Title",
  "content.account.signInButton": "Sign In Button Text",
  "content.account.signUpButton": "Sign Up Button Text",
  "content.account.signOutButton": "Sign Out Button Text",
  "content.account.forgotPasswordLink": "Forgot Password Link",
  "content.account.myAccountTitle": "My Account Title",
  "content.account.ordersTitle": "Orders Title",
  "content.account.addressesTitle": "Addresses Title",
  "content.account.wishlistTitle": "Wishlist Title",
  "content.account.settingsTitle": "Settings Title",
  "content.account.dashboardTitle": "Dashboard Title",
  "content.account.needHelpTitle": "Need Help Title",
  "content.account.needHelpDescription": "Need Help Description",
  "content.account.contactSupportButton": "Contact Support Button",
  "content.account.signInSubtitle": "Sign In Subtitle",
  "content.account.signUpSubtitle": "Sign Up Subtitle",
  "content.account.orContinueWith": "Or Continue With Text",
  "content.account.whyCreateAccount": "Why Create Account Text",
  "content.account.benefitFasterCheckout": "Benefit: Faster Checkout",
  "content.account.benefitTrackOrders": "Benefit: Track Orders",
  "content.account.benefitWishlist": "Benefit: Wishlist",
  "content.account.benefitDiscounts": "Benefit: Discounts",
  "content.account.termsAgreement": "Terms Agreement Text",
  "content.account.termsOfService": "Terms of Service Link",
  "content.account.privacyPolicy": "Privacy Policy Link",
  "content.account.emailLabel": "Email Label",
  "content.account.emailPlaceholder": "Email Placeholder",
  "content.account.passwordLabel": "Password Label",
  "content.account.passwordPlaceholder": "Password Placeholder",
  "content.account.confirmPasswordLabel": "Confirm Password Label",
  "content.account.confirmPasswordPlaceholder": "Confirm Password Placeholder",
  "content.account.firstNameLabel": "First Name Label",
  "content.account.lastNameLabel": "Last Name Label",
  "content.account.createAccountButton": "Create Account Button",
  "content.account.processingText": "Processing Text",
  "content.account.emailConfirmedMessage": "Email Confirmed Message",
  "content.account.canNowSignIn": "Can Now Sign In Text",
  "content.account.switchToSignIn": "Switch to Sign In Link",
  "content.account.accountExistsMessage": "Account Exists Message",
  "content.account.forgotPasswordTitle": "Forgot Password Title",
  "content.account.forgotPasswordSubtitle": "Forgot Password Subtitle",
  "content.account.sendResetLinkButton": "Send Reset Link Button",
  "content.account.forgotPasswordSuccessMessage": "Forgot Password Success",
  "content.account.resetPasswordTitle": "Reset Password Title",
  "content.account.resetPasswordSubtitle": "Reset Password Subtitle",
  "content.account.newPasswordLabel": "New Password Label",
  "content.account.newPasswordPlaceholder": "New Password Placeholder",
  "content.account.invalidResetLinkMessage": "Invalid Reset Link Message",
  "content.account.resetLinkExpiredError": "Reset Link Expired Error",
  "content.account.verifyEmailTitle": "Verify Email Title",
  "content.account.verifyEmailSubtitle": "Verify Email Subtitle",
  "content.account.loginInvalidCredentialsError": "Login Invalid Credentials Error",
  "content.account.loginGenericError": "Login Generic Error",
  "content.account.registerFailedError": "Register Failed Error",
  "content.account.passwordMismatchError": "Password Mismatch Error",
  "content.account.passwordTooShortError": "Password Too Short Error",
  "content.account.passwordResetRateLimitError": "Password Reset Rate Limit Error",

  // ── Checkout Text ──
  "content.checkout.checkoutTitle": "Checkout Page Title",
  "content.checkout.secureCheckout": "Secure Checkout Badge",
  "content.checkout.shippingStep": "Shipping Step Label",
  "content.checkout.paymentStep": "Payment Step Label",
  "content.checkout.confirmationStep": "Confirmation Step Label",
  "content.checkout.contactInfoTitle": "Contact Info Title",
  "content.checkout.contactInfoSubtitle": "Contact Info Subtitle",
  "content.checkout.accountLabel": "Account Label",
  "content.checkout.signOutButton": "Checkout Sign Out Button",
  "content.checkout.guestEmailLabel": "Guest Email Label",
  "content.checkout.guestEmailPlaceholder": "Guest Email Placeholder",
  "content.checkout.createAccountCheckbox": "Create Account Checkbox",
  "content.checkout.passwordLabel": "Checkout Password Label",
  "content.checkout.shippingAddressTitle": "Shipping Address Title",
  "content.checkout.shippingAddressSubtitle": "Shipping Address Subtitle",
  "content.checkout.addAddressButton": "Add Address Button",
  "content.checkout.editAddressButton": "Edit Address Button",
  "content.checkout.changeAddressButton": "Change Address Button",
  "content.checkout.firstNameLabel": "First Name Label",
  "content.checkout.lastNameLabel": "Last Name Label",
  "content.checkout.companyLabel": "Company Label",
  "content.checkout.addressLine1Label": "Address Line 1 Label",
  "content.checkout.addressLine2Label": "Address Line 2 Label",
  "content.checkout.cityLabel": "City Label",
  "content.checkout.countryLabel": "Country Label",
  "content.checkout.countryPlaceholder": "Country Search Placeholder",
  "content.checkout.noCountryFound": "Country Not Found Text",
  "content.checkout.stateLabel": "State/Province Label",
  "content.checkout.postalCodeLabel": "Postal Code Label",
  "content.checkout.phoneLabel": "Phone Label",
  "content.checkout.saveAddressButton": "Save Address Button",
  "content.checkout.cancelButton": "Cancel Button",
  "content.checkout.billingAddressTitle": "Billing Address Title",
  "content.checkout.billingAddressSubtitle": "Billing Address Subtitle",
  "content.checkout.useSameAsShipping": "Use Same as Shipping Checkbox",
  "content.checkout.useSavedAddressButton": "Use Saved Address Button",
  "content.checkout.deliveryMethodsTitle": "Delivery Methods Title",
  "content.checkout.deliveryMethodsSubtitle": "Delivery Methods Subtitle",
  "content.checkout.noShippingMethodsAvailable": "No Shipping Methods Text",
  "content.checkout.businessDaysText": "Business Days Text",
  "content.checkout.freeShippingLabel": "Free Shipping Label",
  "content.checkout.deliveryFreeShippingUnlocked": "Free Shipping Unlocked Text",
  "content.checkout.deliveryFreeShippingNudge": "Free Shipping Nudge Text",
  "content.checkout.deliveryAddMoreForFreeShipping": "Add More For Free Shipping Text",
  "content.checkout.deliveryFreeShippingSelectMethods": "Free Shipping Select Methods Message",
  "content.checkout.shippingSavingsMessage": "Shipping Savings Message",
  "content.checkout.noDeliveryMethodsText": "No Delivery Methods Text",
  "content.checkout.fetchingShippingRates": "Fetching Shipping Rates Text",
  "content.checkout.updatingShippingRates": "Updating Shipping Rates Text",
  "content.checkout.calculateShippingButton": "Calculate Shipping Button",
  "content.checkout.calculatingShippingText": "Calculating Shipping Text",
  "content.checkout.recalculateRatesButton": "Recalculate Rates Button",
  "content.checkout.addressChangedNotice": "Address Changed Notice",
  "content.checkout.shippingFetchErrorText": "Shipping Fetch Error Text",
  "content.checkout.shippingFetchErrorHint": "Shipping Fetch Error Hint",
  "content.checkout.noShippingMethodsHint": "No Shipping Methods Hint",
  "content.checkout.tryAgainButton": "Try Again Button",
  "content.checkout.shippingAddressDetected": "Shipping Address Detected Text",
  "content.checkout.calculateShippingHint": "Calculate Shipping Hint",
  "content.checkout.savingAddressText": "Saving Address Text",
  "content.checkout.paymentTitle": "Payment Title",
  "content.checkout.paymentSubtitle": "Payment Subtitle",
  "content.checkout.paymentMethodLabel": "Payment Method Label",
  "content.checkout.payNowButton": "Pay Now Button",
  "content.checkout.initializingPaymentText": "Initializing Payment Text",
  "content.checkout.paymentSystemUnavailableError": "Payment System Unavailable Error",
  "content.checkout.paymentFormNotReadyError": "Payment Form Not Ready Error",
  "content.checkout.paymentValidationFailedError": "Payment Validation Failed Error",
  "content.checkout.paymentTimeoutError": "Payment Timeout Error",
  "content.checkout.paymentFailedError": "Payment Failed Error",
  "content.checkout.unexpectedPaymentError": "Unexpected Payment Error",
  "content.checkout.paymentSuccessOrderFailedError": "Payment Success Order Failed Error",
  "content.checkout.orderSummaryTitle": "Order Summary Title",
  "content.checkout.itemsCountSingular": "Items Count Singular",
  "content.checkout.itemsCountPlural": "Items Count Plural",
  "content.checkout.productsLabel": "Products Label",
  "content.checkout.quantityLabel": "Quantity Label",
  "content.checkout.addPromoCodeText": "Add Promo Code Text",
  "content.checkout.promoCodeLabel": "Checkout Promo Code Label",
  "content.checkout.promoCodePlaceholder": "Checkout Promo Code Placeholder",
  "content.checkout.applyPromoButton": "Apply Promo Button",
  "content.checkout.removePromoButton": "Remove Promo Button",
  "content.checkout.oneVoucherPerOrderHint": "One Voucher Per Order Hint",
  "content.checkout.replaceVoucherConfirm": "Replace Voucher Confirm Text",
  "content.checkout.subtotalLabel": "Checkout Subtotal Label",
  "content.checkout.shippingLabel": "Checkout Shipping Label",
  "content.checkout.taxLabel": "Tax Label",
  "content.checkout.includesTaxText": "Includes Tax Text",
  "content.checkout.totalLabel": "Checkout Total Label",
  "content.checkout.contactDetails": "Contact Details Section",
  "content.checkout.shippingAddress": "Shipping Address Section",
  "content.checkout.shippingMethod": "Shipping Method Section",
  "content.checkout.paymentMethod": "Payment Method Section",
  "content.checkout.orderSummary": "Order Summary Section",
  "content.checkout.placeOrder": "Place Order Section",
  "content.checkout.placeOrderButton": "Place Order Button Text",
  "content.checkout.processingOrderText": "Processing Order Text",
  "content.checkout.doNotClosePageText": "Do Not Close Page Text",
  "content.checkout.agreementText": "Agreement Text",
  "content.checkout.orderConfirmation": "Order Confirmation Text",
  "content.checkout.thankYouTitle": "Thank You Title",
  "content.checkout.thankYouMessage": "Thank You Message",
  "content.checkout.orderNumberLabel": "Order Number Label",
  "content.checkout.continueShoppingButton": "Continue Shopping Button",
  "content.checkout.viewOrderButton": "View Order Button",
  "content.checkout.orderConfirmedTitle": "Order Confirmed Title",
  "content.checkout.orderConfirmedMessage": "Order Confirmed Message",
  "content.checkout.confirmationSentTo": "Confirmation Sent To Text",
  "content.checkout.whatsNextTitle": "What's Next Title",
  "content.checkout.orderProcessingStep": "Order Processing Step",
  "content.checkout.orderProcessingMessage": "Order Processing Message",
  "content.checkout.shippingNotificationStep": "Shipping Notification Step",
  "content.checkout.shippingNotificationMessage": "Shipping Notification Message",
  "content.checkout.deliveryStep": "Delivery Step",
  "content.checkout.deliveryMessage": "Delivery Message",
  "content.checkout.printReceiptButton": "Print Receipt Button",
  "content.checkout.accountCreatedTitle": "Account Created Title",
  "content.checkout.accountCreatedDescription": "Account Created Description",
  "content.checkout.orderDetailsTitle": "Order Details Title",
  "content.checkout.contactLabel": "Contact Label",
  "content.checkout.requiredFieldError": "Required Field Error",
  "content.checkout.invalidEmailError": "Invalid Email Error",
  "content.checkout.invalidPhoneError": "Invalid Phone Error",
  "content.checkout.selectDeliveryMethodError": "Select Delivery Method Error",
  "content.checkout.deliveryMethodUnavailable": "Delivery Method Unavailable Error",
  "content.checkout.noCheckoutFoundTitle": "No Checkout Found Title",
  "content.checkout.noCheckoutFoundMessage": "No Checkout Found Message",
  "content.checkout.returnToCartButton": "Return to Cart Button",
  "content.checkout.checkoutExpiredTitle": "Checkout Expired Title",
  "content.checkout.checkoutExpiredMessage": "Checkout Expired Message",
  "content.checkout.somethingWentWrongTitle": "Something Went Wrong Title",
  "content.checkout.somethingWentWrongMessage": "Something Went Wrong Message",
  "content.checkout.continueButtonText": "Continue Button Text",
  "content.checkout.signInTitle": "Checkout Sign In Title",
  "content.checkout.signInButton": "Checkout Sign In Button",
  "content.checkout.guestCheckoutButton": "Guest Checkout Button",
  "content.checkout.freeShippingBadge": "Free Shipping Badge",
  "content.checkout.easyReturnsBadge": "Easy Returns Badge",
  "content.checkout.securePaymentBadge": "Secure Payment Badge",
  "content.checkout.sslEncryptionText": "SSL Encryption Text",
  "content.checkout.privacyPolicy": "Privacy Policy Link",
  "content.checkout.termsOfService": "Terms of Service Link",

  // ── Filters Text ──
  "content.filters.sectionTitle": "Filters Section Title",
  "content.filters.clearAllButton": "Clear All Filters Button",
  "content.filters.showResultsButton": "Show Results Button",
  "content.filters.filtersButtonText": "Filters Button Text",
  "content.filters.categoryTitle": "Category Filter Title",
  "content.filters.collectionTitle": "Collection Filter Title",
  "content.filters.brandTitle": "Brand Filter Title",
  "content.filters.sizeTitle": "Size Filter Title",
  "content.filters.colorTitle": "Color Filter Title",
  "content.filters.priceTitle": "Price Filter Title",
  "content.filters.ratingTitle": "Rating Filter Title",
  "content.filters.availabilityTitle": "Availability Filter Title",
  "content.filters.sortByLabel": "Sort By Label",
  "content.filters.searchForText": "Search For Text",
  "content.filters.inStockOnly": "In Stock Only Label",
  "content.filters.onSale": "On Sale Label",
  "content.filters.activeFiltersLabel": "Active Filters Label",
  "content.filters.sortAtoZ": "Sort A to Z Label",
  "content.filters.sortZtoA": "Sort Z to A Label",
  "content.filters.sortPriceLowHigh": "Sort Price Low to High",
  "content.filters.sortPriceHighLow": "Sort Price High to Low",
  "content.filters.sortNewest": "Sort Newest Label",
  "content.filters.sortSale": "Sort Sale Label",
  "content.filters.noProductsTitle": "No Products Found Title",
  "content.filters.noProductsWithFilters": "No Products With Filters Text",
  "content.filters.noProductsEmpty": "No Products Empty Text",
  "content.filters.filteringProducts": "Filtering Products Text",
  "content.filters.loadingMore": "Loading More Products Text",
  "content.filters.seenAllProducts": "Seen All Products Text",
  "content.filters.searchPlaceholder": "Filters Search Placeholder",
  "content.filters.searchProductsTitle": "Search Products Title",
  "content.filters.searchResultsTitle": "Search Results Title",
  "content.filters.resultsCountText": "Results Count Text",
  "content.filters.noResultsMessage": "No Results Message",
  "content.filters.resultsText": "Results Text",
  "content.filters.productsPageTitle": "Products Page Title",
  "content.filters.shopAllButton": "Shop All Button",
  "content.filters.quickAddButton": "Quick Add Button",
  "content.filters.minimumRating": "Minimum Rating Label",
  "content.filters.starsAndUp": "Stars And Up Label",
  "content.filters.starAndUp": "Star And Up Label",
  "content.filters.clearRatingFilter": "Clear Rating Filter",
  "content.filters.minPriceLabel": "Min Price Label",
  "content.filters.maxPriceLabel": "Max Price Label",
  "content.filters.clearPriceFilter": "Clear Price Filter",
  "content.filters.applyPriceFilter": "Apply Price Filter",
  "content.filters.priceUnderLabel": "Price Under Label",
  "content.filters.priceAboveLabel": "Price Above Label",
  "content.filters.priceFromLabel": "Price From Label",
  "content.filters.priceUpToLabel": "Price Up To Label",

  // ── Product Detail Text ──
  "content.productDetail.freeShipping": "Trust Badge: Free Shipping",
  "content.productDetail.securePayment": "Trust Badge: Secure Payment",
  "content.productDetail.easyReturns": "Trust Badge: Easy Returns",
  "content.productDetail.descriptionTab": "Description Tab",
  "content.productDetail.shippingTab": "Shipping Tab",
  "content.productDetail.reviewsTab": "Reviews Tab",
  "content.productDetail.noDescriptionAvailable": "No Description Available Text",
  "content.productDetail.qtyLabel": "Quantity Label",
  "content.productDetail.shareButton": "Share Button",
  "content.productDetail.colorLabel": "Color Label",
  "content.productDetail.sizeLabel": "Size Label",
  "content.productDetail.selectOptionLabel": "Select Option Label",
  "content.productDetail.pleaseSelectSize": "Please Select Size Text",
  "content.productDetail.pleaseSelectOption": "Please Select Option Text",
  "content.productDetail.onlyXLeft": "Only X Left Text",
  "content.productDetail.inStockWithCount": "In Stock With Count Text",
  "content.productDetail.sellingFast": "Selling Fast Text",
  "content.productDetail.savePercent": "Save Percent Text",
  "content.productDetail.reviewSingular": "Review Singular",
  "content.productDetail.reviewPlural": "Review Plural",
  "content.productDetail.zoomInLabel": "Zoom In Label",
  "content.productDetail.zoomOutLabel": "Zoom Out Label",
  "content.productDetail.previousImageLabel": "Previous Image Label",
  "content.productDetail.nextImageLabel": "Next Image Label",
  "content.productDetail.noReviewsYet": "No Reviews Yet Text",
  "content.productDetail.writeReviewTitle": "Write Review Title",
  "content.productDetail.ratingRequired": "Rating Required Label",
  "content.productDetail.reviewTitleRequired": "Review Title Required",
  "content.productDetail.reviewTitlePlaceholder": "Review Title Placeholder",
  "content.productDetail.reviewRequired": "Review Required Label",
  "content.productDetail.reviewPlaceholder": "Review Placeholder",
  "content.productDetail.submitReviewButton": "Submit Review Button",
  "content.productDetail.helpfulButton": "Helpful Button",
  "content.productDetail.verifiedPurchase": "Verified Purchase Label",
  "content.productDetail.editReview": "Edit Review Button",
  "content.productDetail.deleteReview": "Delete Review Button",
  "content.productDetail.allRatings": "All Ratings Filter",
  "content.productDetail.verifiedOnly": "Verified Only Filter",
  "content.productDetail.deleteReviewTitle": "Delete Review Title",
  "content.productDetail.deleteReviewMessage": "Delete Review Confirm Message",
  "content.productDetail.cancelButton": "Cancel Button",
  "content.productDetail.loadingReviews": "Loading Reviews Text",
  "content.productDetail.loadMoreReviews": "Load More Reviews Button",
  "content.productDetail.failedToLoadReviews": "Failed to Load Reviews Error",
  "content.productDetail.failedToSubmitReview": "Failed to Submit Review Error",
  "content.productDetail.mustBeLoggedInToReview": "Must Be Logged In Error",
  "content.productDetail.sizeGuideButton": "Size Guide Button",
  "content.productDetail.sizeGuideTitle": "Size Guide Title",
  "content.productDetail.specificationsTab": "Specifications Tab",
  "content.productDetail.notifyMeButton": "Notify Me Button",
  "content.productDetail.notifyMeTitle": "Notify Me Title",
  "content.productDetail.notifyMeSubmitButton": "Notify Me Submit Button",
  "content.productDetail.notifyMeSuccess": "Notify Me Success Message",
  "content.productDetail.notifyMeError": "Notify Me Error Message",
  "content.productDetail.relatedProductsTitle": "Related Products Title",
  "content.productDetail.relatedProductsSubtitle": "Related Products Subtitle",

  // Dropship Shipping Text (Product Detail)
  "content.productDetail.shippingEstimatedDelivery": "Dropship Estimated Delivery Text",
  "content.productDetail.shippingFreeLabel": "Dropship Free Shipping Label",
  "content.productDetail.shippingProcessingTime": "Dropship Processing Time Text",
  "content.productDetail.shippingTrackingNotice": "Dropship Tracking Notice Text",
  "content.productDetail.shippingWarehouseNotice": "Dropship Warehouse Notice Text",
  "content.productDetail.shippingReturnPolicyNote": "Dropship Return Policy Note",
  "content.productDetail.shippingCarrierLabel": "Dropship Carrier Label Text",
  "content.productDetail.shippingExtendedReturnNote": "Dropship Extended Return Note",

  // ── Account Dashboard Text ──
  "content.dashboard.totalOrders": "Total Orders Label",
  "content.dashboard.wishlistItems": "Wishlist Items Label",
  "content.dashboard.savedAddresses": "Saved Addresses Label",
  "content.dashboard.memberSince": "Member Since Label",
  "content.dashboard.welcomeBack": "Welcome Back Greeting",
  "content.dashboard.welcomeBackMessage": "Welcome Back Message",
  "content.dashboard.recentOrders": "Recent Orders Title",
  "content.dashboard.viewAllButton": "View All Button",
  "content.dashboard.orderLabel": "Order Label",
  "content.dashboard.noOrdersYet": "No Orders Yet Text",
  "content.dashboard.startShopping": "Start Shopping Button",

  // ── Order Tracking Text ──
  "content.orderTracking.title": "Order Tracking Title",
  "content.orderTracking.description": "Order Tracking Description",
  "content.orderTracking.orderNumberLabel": "Order Number Label",
  "content.orderTracking.emailLabel": "Email Label",
  "content.orderTracking.trackButton": "Track Button",
  "content.orderTracking.errorNotFound": "Order Not Found Error",
  "content.orderTracking.errorGeneric": "Generic Tracking Error",
  "content.orderTracking.backToTracking": "Back to Tracking Link",
  "content.orderTracking.createAccountButton": "Create Account Button",
  "content.orderTracking.contactSupportLink": "Contact Support Link",

  // ── Orders Text ──
  "content.orders.myOrdersTitle": "My Orders Title",
  "content.orders.ordersPlacedCount": "Orders Placed Count",
  "content.orders.orderNumber": "Order Number Label",
  "content.orders.orderLabel": "Order Label",
  "content.orders.orderNumberPrefix": "Order Number Prefix",
  "content.orders.datePlaced": "Date Placed Label",
  "content.orders.totalLabel": "Total Label",
  "content.orders.getInvoice": "Get Invoice Button",
  "content.orders.downloadInvoice": "Download Invoice Button",
  "content.orders.viewDetails": "View Details Button",
  "content.orders.trackPackage": "Track Package Button",
  "content.orders.buyAgain": "Buy Again Button",
  "content.orders.showAllOrders": "Show All Orders Button",
  "content.orders.showLess": "Show Less Button",
  "content.orders.noOrders": "No Orders Text",
  "content.orders.noOrdersMessage": "No Orders Message",
  "content.orders.orderStatus": "Order Status Label",
  "content.orders.qtyLabel": "Quantity Label",
  "content.orders.generatingInvoice": "Generating Invoice Text",
  "content.orders.invoiceAvailable": "Invoice Available Text",
  "content.orders.invoicePending": "Invoice Pending Text",
  "content.orders.close": "Close Button",
  "content.orders.trackingModalTitle": "Tracking Modal Title",
  "content.orders.trackingNumberLabel": "Tracking Number Label",
  "content.orders.backToOrders": "Back to Orders Link",
  "content.orders.orderItemsTitle": "Order Items Title",
  "content.orders.viewProduct": "View Product Link",
  "content.orders.orderSummaryTitle": "Order Summary Title",
  "content.orders.subtotalLabel": "Subtotal Label",
  "content.orders.shippingLabel": "Shipping Label",
  "content.orders.shippingFree": "Shipping Free Label",
  "content.orders.shippingAddressTitle": "Shipping Address Title",
  "content.orders.billingAddressTitle": "Billing Address Title",
  "content.orders.shipmentTrackingTitle": "Shipment Tracking Title",
  "content.orders.invoiceTitle": "Invoice Title",
  "content.orders.quickActionsTitle": "Quick Actions Title",
  "content.orders.needHelpTitle": "Need Help Title",
  "content.orders.contactSupportButton": "Contact Support Button",
  "content.orders.viewFaqsButton": "View FAQs Button",
  "content.orders.statusProcessing": "Status: Processing",
  "content.orders.statusShipped": "Status: Shipped",
  "content.orders.statusDelivered": "Status: Delivered",
  "content.orders.statusCanceled": "Status: Canceled",
  "content.orders.statusReturned": "Status: Returned",
  "content.orders.paymentPending": "Payment: Pending",
  "content.orders.paymentPaid": "Payment: Paid",
  "content.orders.paymentRefunded": "Payment: Refunded",
  "content.orders.paymentFailed": "Payment: Failed",
  "content.orders.reorderItems": "Reorder Items Button",
  "content.orders.addingToCart": "Adding to Cart Text",
  "content.orders.itemsAddedToCart": "Items Added to Cart Text",

  // ── Addresses Text ──
  "content.addresses.myAddresses": "My Addresses Title",
  "content.addresses.addressesCount": "Addresses Count Text",
  "content.addresses.noAddressesYet": "No Addresses Yet Text",
  "content.addresses.addAddressButton": "Add Address Button",
  "content.addresses.defaultShipping": "Default Shipping Label",
  "content.addresses.defaultBilling": "Default Billing Label",
  "content.addresses.shippingAndBilling": "Shipping & Billing Label",
  "content.addresses.setAsDefault": "Set as Default Button",
  "content.addresses.noAddresses": "No Addresses Text",
  "content.addresses.noAddressesMessage": "No Addresses Message",
  "content.addresses.addNewAddressTitle": "Add New Address Title",
  "content.addresses.editButton": "Edit Button",
  "content.addresses.editAddressTitle": "Edit Address Title",
  "content.addresses.deleteButton": "Delete Button",
  "content.addresses.deleteConfirmTitle": "Delete Confirm Title",
  "content.addresses.deleteConfirmMessage": "Delete Confirm Message",
  "content.addresses.saving": "Saving Text",
  "content.addresses.saveChanges": "Save Changes Button",
  "content.addresses.cancel": "Cancel Button",

  // ── Wishlist Text ──
  "content.wishlist.myWishlistTitle": "My Wishlist Title",
  "content.wishlist.itemsCount": "Items Count Text",
  "content.wishlist.loadingWishlist": "Loading Wishlist Text",
  "content.wishlist.emptyWishlistTitle": "Empty Wishlist Title",
  "content.wishlist.emptyWishlistMessage": "Empty Wishlist Message",
  "content.wishlist.discoverProductsButton": "Discover Products Button",
  "content.wishlist.clearAllButton": "Clear All Button",
  "content.wishlist.viewProduct": "View Product Button",
  "content.wishlist.outOfStock": "Out of Stock Label",
  "content.wishlist.removeFromWishlist": "Remove From Wishlist",
  "content.wishlist.moveToCart": "Move to Cart Button",

  // ── Settings Text ──
  "content.settings.accountSettings": "Account Settings Title",
  "content.settings.settingsSubtitle": "Settings Subtitle",
  "content.settings.profileInformation": "Profile Information Title",
  "content.settings.saveChangesButton": "Save Changes Button",
  "content.settings.changePassword": "Change Password Title",
  "content.settings.currentPassword": "Current Password Label",
  "content.settings.newPasswordLabel": "New Password Label",
  "content.settings.confirmNewPassword": "Confirm New Password Label",
  "content.settings.updatePasswordButton": "Update Password Button",
  "content.settings.passwordUpdated": "Password Updated Message",
  "content.settings.notificationPreferences": "Notification Preferences Title",
  "content.settings.orderUpdates": "Order Updates Toggle",
  "content.settings.promotionsOffers": "Promotions & Offers Toggle",
  "content.settings.newsletterSetting": "Newsletter Toggle",
  "content.settings.smsNotifications": "SMS Notifications Toggle",
  "content.settings.dangerZone": "Danger Zone Title",
  "content.settings.deleteAccountButton": "Delete Account Button",
  "content.settings.confirmDeleteTitle": "Confirm Delete Title",
  "content.settings.confirmDeleteMessage": "Confirm Delete Message",

  // ── Footer Text ──
  "content.footer.privacyPolicyLink": "Privacy Policy Link",
  "content.footer.termsOfServiceLink": "Terms of Service Link",
  "content.footer.shippingLink": "Shipping Link",
  "content.footer.returnPolicyLink": "Return Policy Link",
  "content.footer.allRightsReserved": "All Rights Reserved Text",
  "content.footer.madeWith": "Made With Text",
  "content.footer.inLocation": "In Location Text",
  "content.footer.contactUs": "Contact Us Text",
  "content.footer.contactUsButton": "Contact Us Button",
  "content.footer.customerService": "Customer Service Text",
  "content.footer.shopTitle": "Shop Section Title",
  "content.footer.companyTitle": "Company Section Title",
  "content.footer.supportTitle": "Support Section Title",
  "content.footer.followUsTitle": "Follow Us Title",
  "content.footer.trackOrderLink": "Track Order Link",

  // ── Navbar Text ──
  "content.navbar.selectChannel": "Select Channel/Currency",
  "content.navbar.searchPlaceholder": "Search Placeholder",
  "content.navbar.viewAllResultsFor": "View All Results For Text",
  "content.navbar.recentlySearchedLabel": "Recently Searched Label",
  "content.navbar.recentSearchesClearLabel": "Recent Searches Clear Label",
  "content.navbar.popularSearchesLabel": "Popular Searches Label",
  "content.navbar.noResultsText": "No Results Text",
  "content.navbar.noResultsHint": "No Results Hint",
  "content.navbar.searchForText": "Search For Text",
  "content.navbar.cartLabel": "Cart Label",
  "content.navbar.accountLabel": "Account Label",
  "content.navbar.menuLabel": "Menu Label",
  "content.navbar.signInText": "Sign In Text",
  "content.navbar.shopAllButton": "Shop All Button",
  "content.navbar.saleButton": "Sale Button",
  "content.navbar.collectionsLabel": "Collections Label",
  "content.navbar.brandsLabel": "Brands Label",
  "content.navbar.categoriesLabel": "Categories Label",
  "content.navbar.viewAllProducts": "View All Products Link",
  "content.navbar.exploreCategoryLabel": "Explore Category Label",
  "content.navbar.subcategoriesSide": "Subcategories Side",
  "content.navbar.mobileNavPosition": "Mobile Nav Position",
  "content.navbar.mobileMenuStyle": "Mobile Menu Style",
  "content.navbar.dropdownArrowDirection": "Dropdown Arrow Direction",
  "content.navbar.homeLabel": "Home Label",
  "content.navbar.shopLabel": "Shop Label",

  // ── Error Text ──
  "content.error.title": "Error Page Title",
  "content.error.description": "Error Page Description",
  "content.error.tryAgainButton": "Try Again Button",
  "content.error.backToHomeButton": "Back to Home Button",
  "content.error.needHelpText": "Need Help Text",
  "content.error.contactSupportLink": "Contact Support Link",

  // ── Not Found Text ──
  "content.notFound.title": "404 Page Title",
  "content.notFound.description": "404 Page Description",
  "content.notFound.backToHomeButton": "Back to Home Button",
  "content.notFound.browseProductsButton": "Browse Products Button",
  "content.notFound.helpfulLinksText": "Helpful Links Text",
  "content.notFound.productNotFoundTitle": "Product Not Found Title",
  "content.notFound.productNotFoundDescription": "Product Not Found Description",

  // ── Cookie Consent Text ──
  "content.cookieConsent.bannerTitle": "Cookie Banner Title",
  "content.cookieConsent.bannerDescription": "Cookie Banner Description",
  "content.cookieConsent.acceptAllButton": "Accept All Cookies Button",
  "content.cookieConsent.rejectAllButton": "Reject All Cookies Button",
  "content.cookieConsent.manageButton": "Manage Cookies Button",
  "content.cookieConsent.essentialLabel": "Essential Cookies Label",
  "content.cookieConsent.analyticsLabel": "Analytics Cookies Label",
  "content.cookieConsent.marketingLabel": "Marketing Cookies Label",
  "content.cookieConsent.savePreferencesButton": "Save Cookie Preferences Button",

  // ── FAQ Text ──
  "content.faq.heroTitle": "FAQ Hero Title",
  "content.faq.heroDescription": "FAQ Hero Description",
  "content.faq.searchPlaceholder": "FAQ Search Placeholder",
  "content.faq.noResultsText": "FAQ No Results Text",
  "content.faq.contactUsButton": "FAQ Contact Us Button",
  "content.faq.callUsButton": "FAQ Call Us Button",

  // ── Contact Text ──
  "content.contact.heroTitle": "Contact Hero Title",
  "content.contact.heroDescription": "Contact Hero Description",
  "content.contact.formTitle": "Contact Form Title",
  "content.contact.nameLabel": "Contact Name Label",
  "content.contact.subjectLabel": "Contact Subject Label",
  "content.contact.messageLabel": "Contact Message Label",
  "content.contact.sendButton": "Send Message Button",
  "content.contact.successTitle": "Contact Success Title",
  "content.contact.faqsTitle": "Contact FAQs Title",

  // ── Pagination Text ──
  "content.pagination.previousButton": "Pagination Previous Button",
  "content.pagination.nextButton": "Pagination Next Button",
  "content.pagination.pageLabel": "Pagination Page Label",

  // ── Component Designer ──
  "componentOverrides": "Component Designer Overrides",
  "componentOverrides.homepage.hero": "Hero Banner Overrides",
  "componentOverrides.homepage.trustStrip": "Trust Strip Overrides",
  "componentOverrides.homepage.marquee": "Marquee Overrides",
  "componentOverrides.homepage.categories": "Categories Section Overrides",
  "componentOverrides.homepage.trending": "Trending Products Overrides",
  "componentOverrides.homepage.promotionBanner": "Promo Banner Overrides",
  "componentOverrides.homepage.flashDeals": "Flash Deals Overrides",
  "componentOverrides.homepage.collectionMosaic": "Collection Mosaic Overrides",
  "componentOverrides.homepage.bestSellers": "Best Sellers Overrides",
  "componentOverrides.homepage.customerFeedback": "Customer Feedback Overrides",
  "componentOverrides.homepage.newsletter": "Newsletter Section Overrides",
  "componentOverrides.plp.filterSidebar": "Filter Sidebar Overrides",
  "componentOverrides.plp.activeFiltersTags": "Active Filters Tags Overrides",
  "componentOverrides.plp.quickFilters": "Quick Filters Overrides",
  "componentOverrides.pdp.gallery": "Product Gallery Overrides",
  "componentOverrides.pdp.addToCart": "Add to Cart Button Overrides",
  "componentOverrides.pdp.addToCartButton": "Add to Cart Button Overrides",
  "componentOverrides.pdp.variantSelector": "Variant Selector Overrides",
  "componentOverrides.pdp.quantitySelector": "Quantity Selector Overrides",
  "componentOverrides.pdp.tabs": "Product Tabs Overrides",
  "componentOverrides.pdp.relatedProducts": "Related Products Overrides",
  "componentOverrides.layout.header": "Header Overrides",
  "componentOverrides.layout.footer": "Footer Overrides",
  "componentOverrides.homepage.brandGrid": "Brand Grid Overrides",
  "componentOverrides.homepage.productCard": "Homepage Product Card Overrides",
  "componentOverrides.plp.productGrid": "Product Grid Overrides",
  "componentOverrides.plp.productCard": "PLP Product Card Overrides",
  "componentOverrides.plp.sortBy": "Sort Dropdown Overrides",
  "componentOverrides.pdp.stickyAddToCart": "Sticky Mobile Add to Cart Overrides",
  "componentOverrides.layout.headerBanner": "Header Banner Overrides",
  "componentOverrides.layout.mobileBottomNav": "Mobile Bottom Nav Overrides",
  "componentOverrides.layout.searchDialog": "Search Dialog Overrides",
  "componentOverrides.cart.drawer": "Cart Drawer Overrides",
  "componentOverrides.cart.page": "Cart Page Overrides",
  "componentOverrides.checkout.page": "Checkout Page Overrides",
  "componentOverrides.checkout.summary": "Checkout Summary Overrides",
  "componentOverrides.checkout.placeOrder": "Place Order Button Overrides",
  "componentOverrides.checkout.contactStep": "Contact Step Overrides",
  "componentOverrides.checkout.shippingStep": "Shipping Step Overrides",
  "componentOverrides.checkout.deliveryStep": "Delivery Step Overrides",
  "componentOverrides.checkout.paymentStep": "Payment Step Overrides",
  "componentOverrides.checkout.confirmation": "Order Confirmation Overrides",
  "componentOverrides.account.dashboard": "Account Dashboard Overrides",
  "componentOverrides.account.orders": "Orders List Overrides",
  "componentOverrides.account.addresses": "Addresses Page Overrides",
  "componentOverrides.account.wishlist": "Wishlist Page Overrides",
  "componentOverrides.account.settings": "Account Settings Overrides",
  "componentOverrides.auth.login": "Login Page Overrides",
  "componentOverrides.auth.forgotPassword": "Forgot Password Page Overrides",
  "componentOverrides.ui.productCard": "Product Card Overrides",
  "componentOverrides.ui.badges": "Badges Overrides",
  "componentOverrides.ui.imageOverlay": "Image Overlay Overrides",
};
