// Protein House — Product Catalog Definition
// 70 supplement products for Saleor Bulk Manager import

export type ProductType =
  | "Protein Powder"
  | "Pre-Workout"
  | "Creatine"
  | "Amino Acids"
  | "Vitamins & Minerals"
  | "Fat Burner"
  | "Functional Food"
  | "Accessories";

export interface ProductDefinition {
  type: ProductType;
  brand: string;
  model: string;
  model_he: string;
  category: string;
  flavor?: string;
  proteinSource?: string;
  stimLevel?: string;
  dietaryTags?: string[];
  goal?: string[];
  basePrice_ILS: number;
  basePrice_USD: number;
  discount?: number;
  collections: string[];
}

// ---------------------------------------------------------------------------
// PROTEIN PRODUCTS (30)
// ---------------------------------------------------------------------------

export const PROTEIN_PRODUCTS: ProductDefinition[] = [
  {
    type: "Protein Powder",
    brand: "Optimum Nutrition",
    model: "Gold Standard 100% Whey",
    model_he: "גולד סטנדרט 100% חלבון מי גבינה",
    category: "whey-protein",
    proteinSource: "Whey Blend",
    dietaryTags: ["Gluten-Free"],
    goal: ["Muscle Building", "Recovery"],
    basePrice_ILS: 249,
    basePrice_USD: 67,
    collections: ["best-sellers", "featured-products", "muscle-building"],
  },
  {
    type: "Protein Powder",
    brand: "Optimum Nutrition",
    model: "Gold Standard 100% Isolate",
    model_he: "גולד סטנדרט 100% אייזולט",
    category: "whey-isolate",
    proteinSource: "Whey Isolate",
    dietaryTags: ["Gluten-Free", "Sugar-Free"],
    goal: ["Muscle Building", "Weight Loss"],
    basePrice_ILS: 319,
    basePrice_USD: 86,
    collections: ["featured-products", "muscle-building", "weight-loss"],
  },
  {
    type: "Protein Powder",
    brand: "Optimum Nutrition",
    model: "Serious Mass",
    model_he: "סיריאס מאס גיינר",
    category: "mass-gainer",
    proteinSource: "Mass Gainer",
    goal: ["Muscle Building"],
    basePrice_ILS: 289,
    basePrice_USD: 78,
    collections: ["muscle-building"],
  },
  {
    type: "Protein Powder",
    brand: "Optimum Nutrition",
    model: "Gold Standard 100% Casein",
    model_he: "גולד סטנדרט 100% קזאין",
    category: "casein-protein",
    proteinSource: "Casein",
    dietaryTags: ["Gluten-Free"],
    goal: ["Recovery"],
    basePrice_ILS: 269,
    basePrice_USD: 73,
    collections: ["recovery"],
  },
  {
    type: "Protein Powder",
    brand: "Dymatize",
    model: "ISO100 Hydrolyzed",
    model_he: "ISO100 חלבון הידרוליזד",
    category: "whey-isolate",
    proteinSource: "Whey Isolate",
    dietaryTags: ["Gluten-Free", "Sugar-Free"],
    goal: ["Muscle Building", "Weight Loss"],
    basePrice_ILS: 329,
    basePrice_USD: 89,
    discount: 15,
    collections: ["best-sellers", "sale", "muscle-building"],
  },
  {
    type: "Protein Powder",
    brand: "Dymatize",
    model: "Elite 100% Whey",
    model_he: "אליט 100% חלבון מי גבינה",
    category: "whey-protein",
    proteinSource: "Whey Blend",
    dietaryTags: ["Gluten-Free"],
    goal: ["Muscle Building"],
    basePrice_ILS: 219,
    basePrice_USD: 59,
    collections: ["beginner-stack"],
  },
  {
    type: "Protein Powder",
    brand: "Dymatize",
    model: "Super Mass Gainer",
    model_he: "סופר מאס גיינר",
    category: "mass-gainer",
    proteinSource: "Mass Gainer",
    goal: ["Muscle Building"],
    basePrice_ILS: 259,
    basePrice_USD: 70,
    collections: ["muscle-building"],
  },
  {
    type: "Protein Powder",
    brand: "MuscleTech",
    model: "Nitro-Tech Whey Gold",
    model_he: "ניטרו-טק חלבון מי גבינה גולד",
    category: "whey-protein",
    proteinSource: "Whey Blend",
    dietaryTags: ["Gluten-Free"],
    goal: ["Muscle Building"],
    basePrice_ILS: 259,
    basePrice_USD: 70,
    collections: ["best-sellers", "muscle-building"],
  },
  {
    type: "Protein Powder",
    brand: "MuscleTech",
    model: "Nitro-Tech 100% Whey Isolate Gold",
    model_he: "ניטרו-טק 100% אייזולט גולד",
    category: "whey-isolate",
    proteinSource: "Whey Isolate",
    dietaryTags: ["Gluten-Free", "Sugar-Free"],
    goal: ["Muscle Building", "Weight Loss"],
    basePrice_ILS: 339,
    basePrice_USD: 92,
    collections: ["muscle-building", "weight-loss"],
  },
  {
    type: "Protein Powder",
    brand: "MuscleTech",
    model: "Mass-Tech Extreme 2000",
    model_he: "מאס-טק אקסטרים 2000",
    category: "mass-gainer",
    proteinSource: "Mass Gainer",
    goal: ["Muscle Building"],
    basePrice_ILS: 299,
    basePrice_USD: 81,
    collections: ["muscle-building"],
  },
  {
    type: "Protein Powder",
    brand: "BSN",
    model: "Syntha-6",
    model_he: "סינטה-6 חלבון מולטי",
    category: "whey-protein",
    proteinSource: "Whey Blend",
    goal: ["Muscle Building", "General Health"],
    basePrice_ILS: 229,
    basePrice_USD: 62,
    collections: ["best-sellers", "beginner-stack"],
  },
  {
    type: "Protein Powder",
    brand: "BSN",
    model: "Syntha-6 Edge",
    model_he: "סינטה-6 אדג' חלבון מי גבינה",
    category: "whey-protein",
    proteinSource: "Whey Blend",
    dietaryTags: ["Gluten-Free"],
    goal: ["Muscle Building"],
    basePrice_ILS: 249,
    basePrice_USD: 67,
    discount: 10,
    collections: ["sale"],
  },
  {
    type: "Protein Powder",
    brand: "BSN",
    model: "True-Mass",
    model_he: "טרו-מאס גיינר",
    category: "mass-gainer",
    proteinSource: "Mass Gainer",
    goal: ["Muscle Building"],
    basePrice_ILS: 279,
    basePrice_USD: 75,
    collections: ["muscle-building"],
  },
  {
    type: "Protein Powder",
    brand: "Cellucor",
    model: "Cor-Performance Whey",
    model_he: "קור-פרפורמנס חלבון מי גבינה",
    category: "whey-protein",
    proteinSource: "Whey Blend",
    dietaryTags: ["Gluten-Free"],
    goal: ["Muscle Building"],
    basePrice_ILS: 199,
    basePrice_USD: 54,
    collections: ["beginner-stack"],
  },
  {
    type: "Protein Powder",
    brand: "MyProtein",
    model: "Impact Whey Protein",
    model_he: "אימפקט חלבון מי גבינה",
    category: "whey-protein",
    proteinSource: "Whey Concentrate",
    dietaryTags: ["Gluten-Free"],
    goal: ["Muscle Building", "General Health"],
    basePrice_ILS: 179,
    basePrice_USD: 48,
    discount: 20,
    collections: ["best-sellers", "sale", "beginner-stack"],
  },
  {
    type: "Protein Powder",
    brand: "MyProtein",
    model: "Impact Whey Isolate",
    model_he: "אימפקט חלבון מי גבינה אייזולט",
    category: "whey-isolate",
    proteinSource: "Whey Isolate",
    dietaryTags: ["Gluten-Free", "Sugar-Free"],
    goal: ["Muscle Building", "Weight Loss"],
    basePrice_ILS: 229,
    basePrice_USD: 62,
    collections: ["weight-loss"],
  },
  {
    type: "Protein Powder",
    brand: "MyProtein",
    model: "Vegan Protein Blend",
    model_he: "תערובת חלבון טבעוני",
    category: "vegan-protein",
    proteinSource: "Plant/Vegan",
    dietaryTags: ["Vegan", "Gluten-Free", "Dairy-Free"],
    goal: ["Muscle Building", "General Health"],
    basePrice_ILS: 189,
    basePrice_USD: 51,
    collections: ["vegan-collection"],
  },
  {
    type: "Protein Powder",
    brand: "Ghost",
    model: "Ghost Whey",
    model_he: "גוסט חלבון מי גבינה",
    category: "whey-protein",
    proteinSource: "Whey Blend",
    dietaryTags: ["Gluten-Free"],
    goal: ["Muscle Building"],
    basePrice_ILS: 269,
    basePrice_USD: 73,
    collections: ["new-arrivals", "featured-products"],
  },
  {
    type: "Protein Powder",
    brand: "Ghost",
    model: "Ghost Vegan Protein",
    model_he: "גוסט חלבון טבעוני",
    category: "vegan-protein",
    proteinSource: "Plant/Vegan",
    dietaryTags: ["Vegan", "Gluten-Free", "Dairy-Free"],
    goal: ["Muscle Building", "General Health"],
    basePrice_ILS: 259,
    basePrice_USD: 70,
    collections: ["new-arrivals", "vegan-collection"],
  },
  {
    type: "Protein Powder",
    brand: "BioTechUSA",
    model: "Iso Whey Zero",
    model_he: "איזו מי גבינה זירו",
    category: "whey-isolate",
    proteinSource: "Whey Isolate",
    dietaryTags: ["Gluten-Free", "Sugar-Free", "Non-GMO"],
    goal: ["Muscle Building", "Weight Loss"],
    basePrice_ILS: 279,
    basePrice_USD: 75,
    collections: ["featured-products", "weight-loss"],
  },
  {
    type: "Protein Powder",
    brand: "BioTechUSA",
    model: "100% Pure Whey",
    model_he: "100% חלבון מי גבינה טהור",
    category: "whey-protein",
    proteinSource: "Whey Concentrate",
    goal: ["Muscle Building", "General Health"],
    basePrice_ILS: 199,
    basePrice_USD: 54,
    collections: ["beginner-stack"],
  },
  {
    type: "Protein Powder",
    brand: "BioTechUSA",
    model: "Vegan Protein",
    model_he: "חלבון טבעוני ביוטק",
    category: "vegan-protein",
    proteinSource: "Plant/Vegan",
    dietaryTags: ["Vegan", "Gluten-Free", "Dairy-Free", "Sugar-Free"],
    goal: ["General Health"],
    basePrice_ILS: 169,
    basePrice_USD: 46,
    collections: ["vegan-collection"],
  },
  {
    type: "Protein Powder",
    brand: "Scitec Nutrition",
    model: "100% Whey Protein Professional",
    model_he: "100% חלבון מי גבינה פרופשיונל",
    category: "whey-protein",
    proteinSource: "Whey Concentrate",
    goal: ["Muscle Building"],
    basePrice_ILS: 209,
    basePrice_USD: 57,
    discount: 15,
    collections: ["sale"],
  },
  {
    type: "Protein Powder",
    brand: "Scitec Nutrition",
    model: "100% Whey Isolate",
    model_he: "100% חלבון מי גבינה אייזולט",
    category: "whey-isolate",
    proteinSource: "Whey Isolate",
    dietaryTags: ["Sugar-Free"],
    goal: ["Muscle Building", "Weight Loss"],
    basePrice_ILS: 289,
    basePrice_USD: 78,
    collections: ["weight-loss"],
  },
  {
    type: "Protein Powder",
    brand: "Rule 1",
    model: "R1 Protein",
    model_he: "R1 חלבון מי גבינה אייזולט",
    category: "whey-isolate",
    proteinSource: "Whey Isolate",
    dietaryTags: ["Gluten-Free", "Sugar-Free"],
    goal: ["Muscle Building"],
    basePrice_ILS: 299,
    basePrice_USD: 81,
    collections: ["new-arrivals"],
  },
  {
    type: "Protein Powder",
    brand: "Rule 1",
    model: "R1 Gain",
    model_he: "R1 גיינר מאס",
    category: "mass-gainer",
    proteinSource: "Mass Gainer",
    goal: ["Muscle Building"],
    basePrice_ILS: 269,
    basePrice_USD: 73,
    collections: ["muscle-building"],
  },
  {
    type: "Protein Powder",
    brand: "Optimum Nutrition",
    model: "Gold Standard Plant Protein",
    model_he: "גולד סטנדרט חלבון צמחי",
    category: "vegan-protein",
    proteinSource: "Plant/Vegan",
    dietaryTags: ["Vegan", "Gluten-Free", "Dairy-Free", "Non-GMO"],
    goal: ["Muscle Building", "General Health"],
    basePrice_ILS: 239,
    basePrice_USD: 65,
    collections: ["vegan-collection", "new-arrivals"],
  },
  {
    type: "Protein Powder",
    brand: "Dymatize",
    model: "ISO100 Clear",
    model_he: "ISO100 קליר חלבון שקוף",
    category: "whey-isolate",
    proteinSource: "Whey Isolate",
    dietaryTags: ["Gluten-Free", "Sugar-Free"],
    goal: ["Recovery", "Weight Loss"],
    basePrice_ILS: 309,
    basePrice_USD: 84,
    collections: ["new-arrivals", "weight-loss"],
  },
  {
    type: "Protein Powder",
    brand: "MuscleTech",
    model: "Nitro-Tech Ripped",
    model_he: "ניטרו-טק ריפד חלבון + שריפת שומן",
    category: "whey-protein",
    proteinSource: "Whey Blend",
    dietaryTags: ["Gluten-Free"],
    goal: ["Weight Loss", "Muscle Building"],
    basePrice_ILS: 279,
    basePrice_USD: 75,
    discount: 20,
    collections: ["sale", "weight-loss"],
  },
  {
    type: "Protein Powder",
    brand: "Ghost",
    model: "Ghost Whey X Chips Ahoy!",
    model_he: "גוסט חלבון מי גבינה X צ'יפס אהוי!",
    category: "whey-protein",
    proteinSource: "Whey Blend",
    dietaryTags: ["Gluten-Free"],
    goal: ["Muscle Building"],
    basePrice_ILS: 289,
    basePrice_USD: 78,
    collections: ["featured-products", "new-arrivals"],
  },
];

// ---------------------------------------------------------------------------
// PERFORMANCE PRODUCTS (25) — Pre-Workout, Creatine, Amino Acids, Fat Burners
// ---------------------------------------------------------------------------

export const PERFORMANCE_PRODUCTS: ProductDefinition[] = [
  // --- Pre-Workout (10) ---
  {
    type: "Pre-Workout",
    brand: "Cellucor",
    model: "C4 Original",
    model_he: "C4 אוריג'ינל פרה וורקאאוט",
    category: "pre-workout-moderate",
    stimLevel: "Moderate",
    dietaryTags: ["Sugar-Free"],
    goal: ["Energy", "Focus"],
    basePrice_ILS: 149,
    basePrice_USD: 40,
    collections: ["best-sellers", "energy-performance"],
  },
  {
    type: "Pre-Workout",
    brand: "Cellucor",
    model: "C4 Ultimate",
    model_he: "C4 אולטימייט פרה וורקאאוט",
    category: "pre-workout-high",
    stimLevel: "High Stim",
    dietaryTags: ["Sugar-Free"],
    goal: ["Energy", "Pump", "Focus"],
    basePrice_ILS: 199,
    basePrice_USD: 54,
    collections: ["featured-products", "energy-performance"],
  },
  {
    type: "Pre-Workout",
    brand: "Optimum Nutrition",
    model: "Gold Standard Pre-Workout",
    model_he: "גולד סטנדרט פרה וורקאאוט",
    category: "pre-workout-moderate",
    stimLevel: "Moderate",
    dietaryTags: ["Sugar-Free", "Gluten-Free"],
    goal: ["Energy", "Endurance"],
    basePrice_ILS: 169,
    basePrice_USD: 46,
    collections: ["best-sellers", "energy-performance"],
  },
  {
    type: "Pre-Workout",
    brand: "Ghost",
    model: "Ghost Legend",
    model_he: "גוסט לג'נד פרה וורקאאוט",
    category: "pre-workout-moderate",
    stimLevel: "Moderate",
    dietaryTags: ["Sugar-Free", "Gluten-Free"],
    goal: ["Energy", "Focus", "Pump"],
    basePrice_ILS: 189,
    basePrice_USD: 51,
    collections: ["new-arrivals", "energy-performance"],
  },
  {
    type: "Pre-Workout",
    brand: "BSN",
    model: "N.O.-Xplode",
    model_he: "N.O.-אקספלוד פרה וורקאאוט",
    category: "pre-workout-high",
    stimLevel: "High Stim",
    goal: ["Energy", "Endurance"],
    basePrice_ILS: 159,
    basePrice_USD: 43,
    discount: 15,
    collections: ["sale", "energy-performance"],
  },
  {
    type: "Pre-Workout",
    brand: "MuscleTech",
    model: "Vapor X5",
    model_he: "ווייפור X5 פרה וורקאאוט",
    category: "pre-workout-high",
    stimLevel: "High Stim",
    dietaryTags: ["Sugar-Free"],
    goal: ["Energy", "Pump"],
    basePrice_ILS: 179,
    basePrice_USD: 48,
    collections: ["energy-performance"],
  },
  {
    type: "Pre-Workout",
    brand: "BioTechUSA",
    model: "Black Blood NOX+",
    model_he: "בלאק בלאד NOX+ פרה וורקאאוט",
    category: "pre-workout-high",
    stimLevel: "High Stim",
    goal: ["Energy", "Pump"],
    basePrice_ILS: 149,
    basePrice_USD: 40,
    collections: ["energy-performance"],
  },
  {
    type: "Pre-Workout",
    brand: "Scitec Nutrition",
    model: "Warp Drive",
    model_he: "וורפ דרייב פרה וורקאאוט",
    category: "pre-workout-moderate",
    stimLevel: "Moderate",
    goal: ["Energy", "Focus"],
    basePrice_ILS: 139,
    basePrice_USD: 38,
    collections: ["beginner-stack", "energy-performance"],
  },
  {
    type: "Pre-Workout",
    brand: "Ghost",
    model: "Ghost Pump",
    model_he: "גוסט פאמפ ללא קפאין",
    category: "pre-workout-stim-free",
    stimLevel: "Stim-Free",
    dietaryTags: ["Sugar-Free", "Vegan"],
    goal: ["Pump"],
    basePrice_ILS: 179,
    basePrice_USD: 48,
    collections: ["vegan-collection", "energy-performance"],
  },
  {
    type: "Pre-Workout",
    brand: "MyProtein",
    model: "THE Pre-Workout",
    model_he: "THE פרה וורקאאוט",
    category: "pre-workout-moderate",
    stimLevel: "Moderate",
    dietaryTags: ["Vegan", "Sugar-Free"],
    goal: ["Energy", "Focus"],
    basePrice_ILS: 129,
    basePrice_USD: 35,
    discount: 25,
    collections: ["sale", "energy-performance"],
  },

  // --- Creatine (5) ---
  {
    type: "Creatine",
    brand: "Optimum Nutrition",
    model: "Micronized Creatine Powder",
    model_he: "קריאטין מיקרונייזד אבקה",
    category: "creatine-monohydrate",
    dietaryTags: ["Vegan", "Gluten-Free", "Sugar-Free"],
    basePrice_ILS: 99,
    basePrice_USD: 27,
    collections: ["best-sellers", "muscle-building", "beginner-stack"],
  },
  {
    type: "Creatine",
    brand: "MuscleTech",
    model: "Cell-Tech Creatine",
    model_he: "סל-טק קריאטין",
    category: "creatine-blend",
    dietaryTags: ["Gluten-Free"],
    basePrice_ILS: 159,
    basePrice_USD: 43,
    collections: ["muscle-building"],
  },
  {
    type: "Creatine",
    brand: "MyProtein",
    model: "Creatine Monohydrate",
    model_he: "קריאטין מונוהידרט",
    category: "creatine-monohydrate",
    dietaryTags: ["Vegan", "Gluten-Free", "Sugar-Free"],
    basePrice_ILS: 79,
    basePrice_USD: 21,
    discount: 10,
    collections: ["sale", "beginner-stack", "muscle-building"],
  },
  {
    type: "Creatine",
    brand: "BioTechUSA",
    model: "100% Creatine Monohydrate",
    model_he: "100% קריאטין מונוהידרט",
    category: "creatine-monohydrate",
    dietaryTags: ["Vegan", "Sugar-Free"],
    basePrice_ILS: 89,
    basePrice_USD: 24,
    collections: ["muscle-building"],
  },
  {
    type: "Creatine",
    brand: "Ghost",
    model: "Ghost Size",
    model_he: "גוסט סייז קריאטין + מאסל בילדר",
    category: "creatine-blend",
    dietaryTags: ["Sugar-Free", "Gluten-Free"],
    basePrice_ILS: 179,
    basePrice_USD: 48,
    collections: ["new-arrivals", "muscle-building"],
  },

  // --- Amino Acids (5) ---
  {
    type: "Amino Acids",
    brand: "Scitec Nutrition",
    model: "BCAA Xpress",
    model_he: "BCAA אקספרס",
    category: "bcaa",
    dietaryTags: ["Vegan", "Sugar-Free"],
    goal: ["Recovery", "Muscle Building"],
    basePrice_ILS: 119,
    basePrice_USD: 32,
    collections: ["recovery"],
  },
  {
    type: "Amino Acids",
    brand: "Optimum Nutrition",
    model: "Gold Standard BCAA Train + Sustain",
    model_he: "גולד סטנדרט BCAA אימון + שיקום",
    category: "bcaa",
    dietaryTags: ["Sugar-Free"],
    goal: ["Recovery", "Muscle Building"],
    basePrice_ILS: 149,
    basePrice_USD: 40,
    collections: ["best-sellers", "recovery"],
  },
  {
    type: "Amino Acids",
    brand: "Ghost",
    model: "Ghost Amino",
    model_he: "גוסט אמינו חומצות אמינו מלאות",
    category: "eaa",
    dietaryTags: ["Sugar-Free", "Vegan"],
    goal: ["Recovery"],
    basePrice_ILS: 159,
    basePrice_USD: 43,
    collections: ["new-arrivals", "recovery"],
  },
  {
    type: "Amino Acids",
    brand: "Dymatize",
    model: "All 9 Amino",
    model_he: "כל 9 חומצות אמינו חיוניות",
    category: "eaa",
    dietaryTags: ["Sugar-Free", "Vegan"],
    goal: ["Recovery", "Muscle Building"],
    basePrice_ILS: 139,
    basePrice_USD: 38,
    collections: ["recovery"],
  },
  {
    type: "Amino Acids",
    brand: "BioTechUSA",
    model: "L-Carnitine 3000",
    model_he: "L-קרניטין 3000",
    category: "l-carnitine",
    dietaryTags: ["Sugar-Free", "Vegan"],
    goal: ["Weight Loss"],
    basePrice_ILS: 99,
    basePrice_USD: 27,
    discount: 20,
    collections: ["sale", "weight-loss"],
  },

  // --- Fat Burners (5) ---
  {
    type: "Fat Burner",
    brand: "MuscleTech",
    model: "Hydroxycut Hardcore Elite",
    model_he: "הידרוקסיקאט הארדקור אליט",
    category: "fat-burner-high",
    stimLevel: "High Stim",
    dietaryTags: ["Gluten-Free"],
    basePrice_ILS: 169,
    basePrice_USD: 46,
    collections: ["best-sellers", "weight-loss"],
  },
  {
    type: "Fat Burner",
    brand: "Cellucor",
    model: "SuperHD Thermogenic",
    model_he: "סופר HD שורף שומן תרמוגני",
    category: "fat-burner-moderate",
    stimLevel: "Moderate",
    dietaryTags: ["Gluten-Free"],
    basePrice_ILS: 149,
    basePrice_USD: 40,
    collections: ["weight-loss"],
  },
  {
    type: "Fat Burner",
    brand: "BSN",
    model: "Hyper Shred",
    model_he: "היפר שרד שורף שומן",
    category: "fat-burner-moderate",
    stimLevel: "Moderate",
    basePrice_ILS: 139,
    basePrice_USD: 38,
    discount: 25,
    collections: ["sale", "weight-loss"],
  },
  {
    type: "Fat Burner",
    brand: "MyProtein",
    model: "Thermopure",
    model_he: "תרמופיור שורף שומן",
    category: "fat-burner-moderate",
    stimLevel: "Moderate",
    dietaryTags: ["Sugar-Free"],
    basePrice_ILS: 119,
    basePrice_USD: 32,
    collections: ["weight-loss", "beginner-stack"],
  },
  {
    type: "Fat Burner",
    brand: "Ghost",
    model: "Ghost Burn",
    model_he: "גוסט ברן שורף שומן",
    category: "fat-burner-stim-free",
    stimLevel: "Stim-Free",
    dietaryTags: ["Vegan", "Sugar-Free"],
    basePrice_ILS: 169,
    basePrice_USD: 46,
    collections: ["new-arrivals", "weight-loss", "vegan-collection"],
  },
];

// ---------------------------------------------------------------------------
// LIFESTYLE PRODUCTS (15) — Vitamins, Functional Food, Accessories
// ---------------------------------------------------------------------------

export const LIFESTYLE_PRODUCTS: ProductDefinition[] = [
  // --- Vitamins & Minerals (5) ---
  {
    type: "Vitamins & Minerals",
    brand: "Optimum Nutrition",
    model: "Opti-Men Multivitamin",
    model_he: "אופטי-מן מולטי ויטמין לגברים",
    category: "multivitamin",
    dietaryTags: ["Gluten-Free"],
    basePrice_ILS: 129,
    basePrice_USD: 35,
    collections: ["best-sellers", "beginner-stack"],
  },
  {
    type: "Vitamins & Minerals",
    brand: "Optimum Nutrition",
    model: "Opti-Women Multivitamin",
    model_he: "אופטי-וומן מולטי ויטמין לנשים",
    category: "multivitamin",
    dietaryTags: ["Gluten-Free"],
    basePrice_ILS: 129,
    basePrice_USD: 35,
    collections: ["best-sellers", "beginner-stack"],
  },
  {
    type: "Vitamins & Minerals",
    brand: "MyProtein",
    model: "Omega-3 Fish Oil",
    model_he: "אומגה-3 שמן דגים",
    category: "omega",
    dietaryTags: ["Gluten-Free"],
    basePrice_ILS: 79,
    basePrice_USD: 21,
    collections: ["beginner-stack"],
  },
  {
    type: "Vitamins & Minerals",
    brand: "BioTechUSA",
    model: "Vitamin D3",
    model_he: "ויטמין D3",
    category: "single-vitamin",
    dietaryTags: ["Gluten-Free", "Sugar-Free"],
    basePrice_ILS: 49,
    basePrice_USD: 13,
    collections: ["beginner-stack"],
  },
  {
    type: "Vitamins & Minerals",
    brand: "Scitec Nutrition",
    model: "ZMB6 Zinc Magnesium B6",
    model_he: "ZMB6 אבץ מגנזיום ויטמין B6",
    category: "mineral-complex",
    dietaryTags: ["Vegan", "Gluten-Free"],
    basePrice_ILS: 69,
    basePrice_USD: 19,
    discount: 15,
    collections: ["sale", "recovery"],
  },

  // --- Functional Food (5) ---
  {
    type: "Functional Food",
    brand: "Optimum Nutrition",
    model: "Protein Bar",
    model_he: "חטיף חלבון אופטימום",
    category: "protein-bar",
    dietaryTags: ["Gluten-Free"],
    basePrice_ILS: 15,
    basePrice_USD: 4,
    collections: ["featured-products"],
  },
  {
    type: "Functional Food",
    brand: "BSN",
    model: "Protein Crisp Bar",
    model_he: "חטיף חלבון קריספ",
    category: "protein-bar",
    basePrice_ILS: 13,
    basePrice_USD: 4,
    collections: ["featured-products"],
  },
  {
    type: "Functional Food",
    brand: "MyProtein",
    model: "Layered Protein Bar",
    model_he: "חטיף חלבון שכבות",
    category: "protein-bar",
    dietaryTags: ["Gluten-Free"],
    basePrice_ILS: 12,
    basePrice_USD: 3,
    discount: 30,
    collections: ["sale"],
  },
  {
    type: "Functional Food",
    brand: "Ghost",
    model: "Ghost Protein Cereal",
    model_he: "גוסט דגני בוקר חלבון",
    category: "protein-snack",
    dietaryTags: ["Gluten-Free"],
    basePrice_ILS: 49,
    basePrice_USD: 13,
    collections: ["new-arrivals"],
  },
  {
    type: "Functional Food",
    brand: "BioTechUSA",
    model: "Protein Pancake Mix",
    model_he: "תערובת פנקייק חלבון",
    category: "baking-mix",
    basePrice_ILS: 59,
    basePrice_USD: 16,
    collections: ["featured-products"],
  },

  // --- Accessories (5) ---
  {
    type: "Accessories",
    brand: "Optimum Nutrition",
    model: "ON Shaker Bottle 700ml",
    model_he: "שייקר ON 700 מ\"ל",
    category: "shaker-bottle",
    basePrice_ILS: 49,
    basePrice_USD: 13,
    collections: ["beginner-stack"],
  },
  {
    type: "Accessories",
    brand: "Ghost",
    model: "Ghost Shaker Bottle",
    model_he: "שייקר גוסט",
    category: "shaker-bottle",
    basePrice_ILS: 59,
    basePrice_USD: 16,
    collections: ["new-arrivals"],
  },
  {
    type: "Accessories",
    brand: "MyProtein",
    model: "Lifting Straps",
    model_he: "רצועות הרמה מיי פרוטאין",
    category: "lifting-straps",
    basePrice_ILS: 49,
    basePrice_USD: 13,
    collections: ["muscle-building"],
  },
  {
    type: "Accessories",
    brand: "BioTechUSA",
    model: "Austin 7 Pill Box",
    model_he: "קופסת כדורים אוסטין 7 ימים",
    category: "pill-box",
    basePrice_ILS: 39,
    basePrice_USD: 11,
    collections: ["beginner-stack"],
  },
  {
    type: "Accessories",
    brand: "Cellucor",
    model: "C4 Gym Bag",
    model_he: "תיק ספורט C4",
    category: "gym-bag",
    basePrice_ILS: 179,
    basePrice_USD: 48,
    discount: 10,
    collections: ["sale", "featured-products"],
  },
];

// ---------------------------------------------------------------------------
// ALL PRODUCTS — Combined export (70 total)
// ---------------------------------------------------------------------------

export const ALL_PRODUCTS: ProductDefinition[] = [
  ...PROTEIN_PRODUCTS,
  ...PERFORMANCE_PRODUCTS,
  ...LIFESTYLE_PRODUCTS,
];
