# Generated by Django 5.2.8 on 2026-01-13 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0095_repopulate_user_number_of_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the subscription is active')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, help_text="Where the subscription came from (e.g., 'homepage', 'checkout')", max_length=100)),
                ('user', models.ForeignKey(blank=True, help_text='User account if subscribed while logged in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_subscriptions', to='account.user')),
            ],
            options={
                'ordering': ('-subscribed_at',),
                'indexes': [models.Index(fields=['email', 'is_active'], name='account_new_email_b650a5_idx'), models.Index(fields=['user', 'is_active'], name='account_new_user_id_1a16ef_idx'), models.Index(fields=['is_active', '-subscribed_at'], name='account_new_is_acti_9b7fcb_idx')],
            },
        ),
    ]
