# Generated by Django 5.2.8 on 2026-01-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0097_contactsubmission'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contactsubmission',
            new_name='account_con_channel_2ee8d3_idx',
            old_name='account_con_channel_created_idx',
        ),
        migrations.RenameIndex(
            model_name='contactsubmission',
            new_name='account_con_status_1b3e8c_idx',
            old_name='account_con_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='contactsubmission',
            new_name='account_con_email_97757f_idx',
            old_name='account_con_email_created_idx',
        ),
        migrations.RenameIndex(
            model_name='contactsubmission',
            new_name='account_con_created_50ef74_idx',
            old_name='account_con_created_at_idx',
        ),
    ]
