# Generated by Django 5.2.8 on 2026-01-24 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0098_rename_account_con_channel_created_idx_account_con_channel_2ee8d3_idx_and_more'),
        ('channel', '0026_channel_automatic_completion_cut_off_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='channel',
            field=models.ForeignKey(blank=True, help_text='Channel where the subscription was made', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_subscriptions', to='channel.channel'),
        ),
        migrations.AddIndex(
            model_name='newslettersubscription',
            index=models.Index(fields=['channel', 'is_active'], name='account_new_channel_702a72_idx'),
        ),
    ]
